### ISSUE TITLE
TypeError: register() got an unexpected keyword argument 'base_name'

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#102]
## What component is this about ?

API server

## What is happening ?

Due to the 3.11 django-rest-framework release today, base_name was removed in favor of basename, resulting in the following exception when attempting to launch the server:
```
TASK [ara_api : Run SQL migrations]
Traceback (most recent call last):
  File "/home/zuul/.ara-tests/virtualenv/bin/ara-manage", line 10, in <module>
    sys.exit(main())
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/ara/server/__main__.py", line 47, in main
    execute_from_command_line(sys.argv)
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/ara/server/urls.py", line 44, in <module>
    path("api/v1/", include("ara.api.urls")),
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zuul/.ara-tests/virtualenv/lib64/python3.7/site-packages/ara/api/urls.py", line 23, in <module>
    router.register("labels", views.LabelViewSet, base_name="label")
TypeError: register() got an unexpected keyword argument 'base_name'
ERROR
{
  "delta": "0:00:00.854477",
  "end": "2019-12-12 16:03:56.755711",
  "msg": "non-zero return code",
  "rc": 1,
  "start": "2019-12-12 16:03:55.901234"
}
```

This will be fixed by https://review.opendev.org/#/c/698781/

**Comment by dmsimard** [comment]
Merged: https://github.com/ansible-community/ara/commit/84cb73eae3c1ebf43a241c304e40515deac8d1c1
Will be in 1.3.2.
