### ISSUE TITLE
Ara_playbook is erroring out in the playbook

### ISSUE THREAD

**Issue by saranyasridharan** [ansible-community/ara#120]
I have copied ara_playbook from the github and set action plugin and tried to run playbook as below.

# What component is this about ?
Plugin: Ara_playbook  action plugin 
 What is your ARA installation like ?
Ansible:
Ara: 1.3 
Installed: from pip command
Environment: virtualenv
Linux environment: Centos 7.2
Database driver: Aws RDS postgres

# What is happening ?
```
ansible-playbook -v sample_playbook.yml
No config file found; using defaults
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Operations to perform:
  Apply all migrations: admin, api, auth, contenttypes, db, sessions
Running migrations:
  No migrations to apply.
PLAY [Test playbook] ********************************************************************************************************************
TASK [Gathering Facts] ******************************************************************************************************************
ok: [localhost]
TASK [Get the currently running playbook] ***********************************************************************************************
Internal Server Error: /api/v1/plays
Traceback (most recent call last):
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedFunction: operator does not exist: text = uuid
LINE 1: ...*) AS "__count" FROM "plays" WHERE "plays"."uuid" = '0abdbda...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/build/araenv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/pagination.py", line 373, in paginate_queryset
    self.count = self.get_count(queryset)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/pagination.py", line 510, in get_count
    return queryset.count()
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/models/query.py", line 392, in count
    return self.query.get_count(using=self.db)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 504, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 489, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1133, in execute_sql
    cursor.execute(sql, params)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: operator does not exist: text = uuid
LINE 1: ...*) AS "__count" FROM "plays" WHERE "plays"."uuid" = '0abdbda...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
2020-04-06 09:06:53,582 ERROR django.request: Internal Server Error: /api/v1/plays
Traceback (most recent call last):
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedFunction: operator does not exist: text = uuid
LINE 1: ...*) AS "__count" FROM "plays" WHERE "plays"."uuid" = '0abdbda...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/build/araenv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/pagination.py", line 373, in paginate_queryset
    self.count = self.get_count(queryset)
  File "/home/build/araenv/lib64/python3.6/site-packages/rest_framework/pagination.py", line 510, in get_count
    return queryset.count()
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/models/query.py", line 392, in count
    return self.query.get_count(using=self.db)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 504, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 489, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1133, in execute_sql
    cursor.execute(sql, params)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/build/araenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: operator does not exist: text = uuid
LINE 1: ...*) AS "__count" FROM "plays" WHERE "plays"."uuid" = '0abdbda...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
2020-04-06 09:06:53,629 ERROR ara.clients.http: Failed to get on /api/v1/plays?uuid=0abdbda0-6b67-f8a3-b552-000000000005: {'params': {}}
2020-04-06 09:06:53,629 ERROR ara.clients.http: Failed to get on /api/v1/plays?uuid=0abdbda0-6b67-f8a3-b552-000000000005: {'params': {}}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
PLAY RECAP ******************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

# What should be happening ?
I expect to get playbook id when I query it from ara_playbook 

This is my playbook:
```
cat sample_playbook.yml
- name: Test playbook
  connection: local
  hosts: localhost
  tasks:
    - name: Get the currently running playbook
      ara_playbook:
      register: playbook_query
    - name: Get failed tasks for the currently running playbook
      vars:
        playbook_id: "{{ playbook_query.playbook.id | string }}"
      set_fact:
        playbook_id: "{{ playbook_id }}"
    - debug:
        msg: "{{ playbook_id }}"
```

**Comment by dmsimard** [comment]
Hi @saranyasridharan and thanks for the issue,

Are you able to try and see if you can reproduce the issue with a vanilla postgresql server ? 

I'm not familiar enough with AWS to be able to tell if there's any gotchas to look out for.

I do not have access to RDS to troubleshoot but the latest integration tests with a vanilla postgresql 10 were [successful](https://storage.bhs.cloud.ovh.net/v1/AUTH_dcaab5e32b234d56b626f72581e3644c/zuul_opendev_logs_47b/712593/1/check/ara-api-postgresql/47b9d92/ara-report/reports/a039d834-008e-41a6-857d-ed15191a0085.html) (note: link will expire in a few days)

**Comment by saranyasridharan** [comment]
Thanks for looking at it David. I will try and let you know.

**Comment by saranyasridharan** [comment]
It worked after installing Ara1.4.0 , may be I missed to copy some dependancy  file last time while I was trying.
