### ISSUE TITLE
AttributeError: 'str' object has no attribute 'to_list'

### ISSUE THREAD

**Issue by berendt** [ansible-community/ara#125]
ARA version: 1.4.0

Trying to initialize my database with ``ara-manage migrate``.  For configuration I am using an environment file with ``ARA_ALLOWED_HOSTS="['api.ara.example.org', 'web.ara.example.org']"``.

``ara-manage migrate`` failed:

```
[ara] No setting found for SECRET_KEY. Generating a random key...
[ara] Creating data & configuration directory: /home/ara-server/.ara/server
Traceback (most recent call last):
  File "/usr/local/bin/ara-manage", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ara/server/__main__.py", line 41, in main
    if not os.path.exists(settings.ARA_SETTINGS):
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/ara/server/settings.py", line 248, in <module>
    ALLOWED_HOSTS=ALLOWED_HOSTS.to_list(),
AttributeError: 'str' object has no attribute 'to_list'
database migration failed, trying again in 10 seconds
```

**Comment by dmsimard** [comment]
Hi @berendt and thanks for the issue !

Could you look at https://github.com/ansible-community/ara/issues/115 and let me know if you're experiencing the same thing ?

It looks like an unexpectedly backwards incompatible change got introduced but it's fixable.

**Comment by berendt** [comment]
I think this is the problem. In the docs at https://ara.readthedocs.io/en/latest/api-configuration.html the sample value is ``export ARA_ALLOWED_HOSTS="['api.ara.example.org', 'web.ara.example.org']"``. But this does not work.

**Comment by berendt** [comment]
```
~ $ pip3 list | grep dynaconf
dynaconf            2.2.3     
```

**Comment by dmsimard** [comment]
@berendt For some reason I can't reproduce the issue locally with neither bash or fish shells.

When you say "environment file", what do you mean exactly ? Is it a bash file that you source ? Something else ?

**Comment by berendt** [comment]
It is an environment file for Docker Compose.

**Comment by dmsimard** [comment]
@berendt oh wow, that's tricky !

Somewhat related, I'm currently iterating on an approach to running the API server in containers -- it relies on ``settings.yaml`` instead of environment variables because lists and dicts are easier in YAML than they are in-line as demonstrated here :p

Would you like to have a look and let me know what you think ? See here:
https://review.opendev.org/#/c/687905/ (or temporarily rendered: https://b9b2bad84b6336395177-a0a9854041c32c7a9a77a079b0ea6637.ssl.cf1.rackcdn.com/687905/7/check/openstack-tox-docs/1a5df2c/docs/container-images.html )

It's still WIP but your input would be appreciated, thanks !
