### ISSUE TITLE
Traceback in API browser: TypeError at /api/v1/playbooks/1 unhashable type: 'dict'

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#131]
## What component is this about ?

API Browser

## What is your ARA installation like ?

Latest master (1.4.1.dev26)

## What is happening ?

I'm able to browse the playbook through the UI just fine but if I query the API for the same playbook it fails:
![Screenshot from 2020-05-14 11-30-20](https://user-images.githubusercontent.com/1291204/81954232-9b580b80-95d6-11ea-9eed-1d8f21019567.png)

```
2020-05-14 15:29:56,785 ERROR django.request: Internal Server Error: /api/v1/playbooks/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 695, in get_context
    'put_form': self.get_rendered_html_form(data, view, 'PUT', request),
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 511, in get_rendered_html_form
    return self.render_form_for_serializer(serializer)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 518, in render_form_for_serializer
    return form_renderer.render(
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 372, in render
    return template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/templatetags/rest_framework.py", line 87, in render_field
    return renderer.render_field(field, style)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 351, in render_field
    return template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 161, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/relations.py", line 551, in iter_options
    self.get_choices(cutoff=self.html_cutoff),
  File "/usr/local/lib/python3.8/site-packages/rest_framework/relations.py", line 539, in get_choices
    return self.child_relation.get_choices(cutoff)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/relations.py", line 197, in get_choices
    return OrderedDict([
TypeError: unhashable type: 'dict'
```

Same thing for ``/api/v1/playbooks``.

If I had to take a guess, it looks like it's related to playbook labels because I am unable to reproduce the issue for the same playbook without labels.

## What should be happening ?

It should work :)

**Comment by dmsimard** [comment]
We had a pretty good case of a documented issue in DRF: https://github.com/encode/django-rest-framework/issues/5141

I'll send a patch to work around it.

**Comment by dmsimard** [comment]
The patch: https://review.opendev.org/#/c/731010/
Will land in 1.4.1.
