### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml' when running the API server or ara-manage commands

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#146]
## What component is this about ?

API server

## What is happening ?

When trying to launch commands with ``ara-manage`` or the API server, ``settings.py`` will raise an exception:

```
Traceback (most recent call last):
  File ".tox/linters/bin/ara-manage", line 10, in <module>
    sys.exit(main())
  File "/home/dmsimard/dev/git/ansible-community/ara/ara/server/__main__.py", line 41, in main
    if not os.path.exists(settings.ARA_SETTINGS):
  File "/home/dmsimard/dev/git/ansible-community/ara/.tox/linters/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/dmsimard/dev/git/ansible-community/ara/.tox/linters/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/dmsimard/dev/git/ansible-community/ara/.tox/linters/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/dmsimard/dev/git/ansible-community/ara/.tox/linters/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dmsimard/dev/git/ansible-community/ara/ara/server/settings.py", line 23, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

This is because ``settings.py`` imports yaml (PyYAML) but it stopped being installed automatically with a recent dynaconf release 3.0.0 where they changed to [ruamel.yaml](https://github.com/rochacbruno/dynaconf/commit/d5cf87cbbdf54625ccf1138a4e4c210956791e61) instead. The exception happens because we don't have PyYAML as an explicit dependency so it doesn't get installed anymore.

## What should be happening ?

We don't really mind if we use one or the other because the only thing we use it for is to write a relatively simple ``settings.yaml`` configuration file so I've submitted a fix where we could also use either: https://review.opendev.org/#/c/738947/

**Comment by robertdebock** [comment]
Ran into this issue as well, thanks for the work!

How are you David? I'm fine, even though Ansible Fest will be a virtual event. ;-)

**Comment by dmsimard** [comment]
Hey @robertdebock, long time no see ! We should catch up virtually on slack or IRC soon but I've been fine :)

I didn't plan on tagging a new release just yet with some things that are WIP but I'll tag a 1.4.2 once the fix lands because otherwise the regression will hurt.

**Comment by dmsimard** [comment]
Pushed out a 1.4.2rc1 and tested that the fix works properly:
```
┬─[dmsimard@localhost:~/d/g/a/ara]─[02:48:26 PM]─[G:1.4.2rc1]
╰─>$ python3 -m venv /tmp/ara-rc
┬─[dmsimard@localhost:~/d/g/a/ara]─[02:48:33 PM]─[G:1.4.2rc1]
╰─>$ /tmp/ara-rc/bin/pip install ara[server]==1.4.2.0rc1
Collecting ara[server]==1.4.2.0rc1
  Downloading https://files.pythonhosted.org/packages/c4/1c/325c7aae8e573bc465c25640d905211c01802ed711eb0b30fc015f57825e/ara-1.4.2.0rc1-py2.py3-none-any.whl (385kB)
     |████████████████████████████████| 389kB 1.4MB/s 
Collecting pbr!=2.1.0,>=2.0.0
  Using cached https://files.pythonhosted.org/packages/96/ba/aa953a11ec014b23df057ecdbc922fdb40ca8463466b1193f3367d2711a6/pbr-5.4.5-py2.py3-none-any.whl
Collecting requests>=2.14.2
  Using cached https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl
Collecting django-filter; extra == "server"
  Using cached https://files.pythonhosted.org/packages/35/94/e516d7f41adecb9fd280c89feceb98fa58f6966a583035c8016ed455c4e5/django_filter-2.3.0-py3-none-any.whl
Collecting whitenoise; extra == "server"
  Using cached https://files.pythonhosted.org/packages/60/24/88ac8f9f7090effc2a554d76c05f5303ef280c1e1c97d056cf35090b28e1/whitenoise-5.1.0-py2.py3-none-any.whl
Collecting dynaconf[yaml]; extra == "server"
  Using cached https://files.pythonhosted.org/packages/1b/d8/8994ffc917a16d85a08026528c66a91fff920d733a48b11fa59a7a510ea7/dynaconf-3.0.0-py2.py3-none-any.whl
Collecting Django<3.0,>=2.1.5; extra == "server"
  Using cached https://files.pythonhosted.org/packages/f2/6c/f7e0ed3d07952742439be43e7fb5a8b07b065ab927c6493be2a6cea59f33/Django-2.2.14-py3-none-any.whl
Collecting tzlocal; extra == "server"
  Using cached https://files.pythonhosted.org/packages/5d/94/d47b0fd5988e6b7059de05720a646a2930920fff247a826f61674d436ba4/tzlocal-2.1-py2.py3-none-any.whl
Collecting djangorestframework>=3.9.1; extra == "server"
  Using cached https://files.pythonhosted.org/packages/be/5b/9bbde4395a1074d528d6d9e0cc161d3b99bd9d0b2b558ca919ffaa2e0068/djangorestframework-3.11.0-py3-none-any.whl
Collecting django-cors-headers; extra == "server"
  Using cached https://files.pythonhosted.org/packages/ef/33/564bb4aeb48a89f91d716e05cdeed7defbf8c74ae4d95de80fbd87590750/django_cors_headers-3.4.0-py3-none-any.whl
Collecting django-health-check; extra == "server"
  Using cached https://files.pythonhosted.org/packages/1c/b3/f2f878ab4ff171b2232d590ed8bd414177f57c0cbf6f3a944b38e6e95e1a/django_health_check-3.12.1-py2.py3-none-any.whl
Collecting pygments; extra == "server"
  Using cached https://files.pythonhosted.org/packages/2d/68/106af3ae51daf807e9cdcba6a90e518954eb8b70341cee52995540a53ead/Pygments-2.6.1-py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<3,>=2.5
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting certifi>=2017.4.17
  Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
Collecting ruamel.yaml; extra == "yaml"
  Using cached https://files.pythonhosted.org/packages/a6/92/59af3e38227b9cc14520bf1e59516d99ceca53e3b8448094248171e9432b/ruamel.yaml-0.16.10-py2.py3-none-any.whl
Collecting pytz
  Using cached https://files.pythonhosted.org/packages/4f/a4/879454d49688e2fad93e59d7d4efda580b783c745fd2ec2a3adf87b0808d/pytz-2020.1-py2.py3-none-any.whl
Collecting sqlparse>=0.2.2
  Using cached https://files.pythonhosted.org/packages/85/ee/6e821932f413a5c4b76be9c5936e313e4fc626b33f16e027866e1d60f588/sqlparse-0.3.1-py2.py3-none-any.whl
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9"
  Using cached https://files.pythonhosted.org/packages/19/0f/f05f7d819bf58196f1007f5e05a14c6ba35d85b1d372ba94afa14a3886fe/ruamel.yaml.clib-0.2.0-cp38-cp38-manylinux1_x86_64.whl
Installing collected packages: pbr, urllib3, chardet, idna, certifi, requests, pytz, sqlparse, Django, django-filter, whitenoise, ruamel.yaml.clib, ruamel.yaml, dynaconf, tzlocal, djangorestframework, django-cors-headers, django-health-check, pygments, ara
Successfully installed Django-2.2.14 ara-1.4.2.0rc1 certifi-2020.6.20 chardet-3.0.4 django-cors-headers-3.4.0 django-filter-2.3.0 django-health-check-3.12.1 djangorestframework-3.11.0 dynaconf-3.0.0 idna-2.10 pbr-5.4.5 pygments-2.6.1 pytz-2020.1 requests-2.24.0 ruamel.yaml-0.16.10 ruamel.yaml.clib-0.2.0 sqlparse-0.3.1 tzlocal-2.1 urllib3-1.25.9 whitenoise-5.1.0
WARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
┬─[dmsimard@localhost:~/d/g/a/ara]─[02:48:55 PM]─[G:1.4.2rc1]
╰─>$ /tmp/ara-rc/bin/ara-manage --help
[ara] No setting found for SECRET_KEY. Generating a random key...
[ara] Using settings file: /home/dmsimard/.ara/server/settings.yaml

Type 'ara-manage help <subcommand>' for help on a specific subcommand.

Available subcommands:

[api]
    prune

[auth]
    changepassword
    createsuperuser

[...]
```

Tagging and releasing 1.4.2.

**Comment by dmsimard** [comment]
And it's a wrap, 1.4.2 is available on PyPi: https://pypi.org/project/ara/1.4.2 :tada:
