### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by watsonb** [ansible-community/ara#160]
## What is the issue ?

Can no longer post reports to ARA on new server install.  I just installed a new ARA API server today and, during playbook runs I see the following errors:

```bash
11:16:04  [WARNING]: Failure using method (v2_playbook_on_stats) in callback plugin
11:16:04  (<ansible.plugins.callback.ara_default.CallbackModule object at
11:16:04  0x7ffb12c550f0>): 'NoneType' object is not subscriptable
11:16:04  --> Scenario: 'default'
11:16:04  --> Action: 'create'
11:16:07  Failed to post on /api/v1/playbooks: {'ansible_version': '2.9.12', 'started': '2020-08-21T16:16:07.516661', 'path': '/usr/local/home/jenkins/workspace/workspace/ar_vmware_instance_master/ar_vmware_instance/molecule/resources/playbooks/create.yml', 'arguments': {'ssh_extra_args': '', 'force_handlers': False, 'ssh_common_args': '', 'vault_password_files': (), 'syntax': False, 'remote_user': None, 'flush_cache': False, 'skip_tags': ('notest', 'molecule-notest'), 'listtags': False, 'listtasks': False, 'step': False, 'sftp_extra_args': '', 'listhosts': False, 'ask_pass': False, 'check': False, 'forks': 50, 'subset': None, 'start_at_task': None, 'args': ('/usr/local/home/jenkins/workspace/workspace/ar_vmware_instance_master/ar_vmware_instance/molecule/resources/playbooks/create.yml',), 'tags': ('all',), 'version': None, 'timeout': 10, 'become_user': None, 'private_key_file': None, 'scp_extra_args': '', 'become_method': 'sudo', 'vault_ids': (), 'become_ask_pass': False, 'verbosity': 0, 'extra_vars': "Not saved by ARA as configured by 'ignored_arguments'", 'inventory': ('/usr/local/home/jenkins/workspace/workspace/ar_vmware_instance_master/ar_vmware_instance/molecule/ephemeral/inventory',), 'module_path': None, 'connection': 'smart', 'diff': False, 'ask_vault_pass': False, 'become': False}, 'status': 'running'}
11:16:07  Failed to post on /api/v1/playbooks: {'ansible_version': '2.9.12', 'started': '2020-08-21T16:16:07.516661', 'path': '/usr/local/home/jenkins/workspace/workspace/ar_vmware_instance_master/ar_vmware_instance/molecule/resources/playbooks/create.yml', 'arguments': {'ssh_extra_args': '', 'force_handlers': False, 'ssh_common_args': '', 'vault_password_files': (), 'syntax': False, 'remote_user': None, 'flush_cache': False, 'skip_tags': ('notest', 'molecule-notest'), 'listtags': False, 'listtasks': False, 'step': False, 'sftp_extra_args': '', 'listhosts': False, 'ask_pass': False, 'check': False, 'forks': 50, 'subset': None, 'start_at_task': None, 'args': ('/usr/local/home/jenkins/workspace/workspace/ar_vmware_instance_master/ar_vmware_instance/molecule/resources/playbooks/create.yml',), 'tags': ('all',), 'version': None, 'timeout': 10, 'become_user': None, 'private_key_file': None, 'scp_extra_args': '', 'become_method': 'sudo', 'vault_ids': (), 'become_ask_pass': False, 'verbosity': 0, 'extra_vars': "Not saved by ARA as configured by 'ignored_arguments'", 'inventory': ('/usr/local/home/jenkins/workspace/workspace/ar_vmware_instance_master/ar_vmware_instance/molecule/ephemeral/inventory',), 'module_path': None, 'connection': 'smart', 'diff': False, 'ask_vault_pass': False, 'become': False}, 'status': 'running'}
11:16:07  [WARNING]: Failure using method (v2_playbook_on_start) in callback plugin
11:16:07  (<ansible.plugins.callback.ara_default.CallbackModule object at
11:16:07  0x7fe377f7de80>): Expecting value: line 1 column 1 (char 0)
11:16:07      
11:16:07      PLAY [PLAY | Setup] ************************************************************
11:16:07  [WARNING]: Failure using method (v2_playbook_on_play_start) in callback plugin
11:16:07  (<ansible.plugins.callback.ara_default.CallbackModule object at
11:16:07  0x7fe377f7de80>): 'NoneType' object is not subscriptable
11:16:08      
11:16:08      TASK [COMMAND | Flush local ip cache] ******************************************
11:16:08  [WARNING]: Failure using method (v2_playbook_on_task_start) in callback plugin
11:16:08  (<ansible.plugins.callback.ara_default.CallbackModule object at
11:16:08  0x7fe377f7de80>): 'NoneType' object is not subscriptable
11:16:08      ok: [knemol-ar-vmware-instance-centos7-master.kiewittest.com]
11:16:08  [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
11:16:08  (<ansible.plugins.callback.ara_default.CallbackModule object at
11:16:08  0x7fe377f7de80>): 'NoneType' object is not subscriptable
```

## What should be happening ?

I setup a fresh ARA server two days ago and this all worked.  The only change is that my playbooks are now pointing to the new server.  I installed from source from master using the recordsansible collection and ara_api Ansible role.

It seems some commits after this one broke things:

Author: David Moreau Simard <moi@dmsimard.com>
Date:   Tue Aug 18 18:32:32 2020 -0400

    Simplify github issue templates
    
    Change-Id: Ic9dbb95a3be0e4ea6432b236ef95ec53343913c7

The commit above is the last one in the git log on my functional server.  

On my new server, there are a few more git log messages (see below)

commit d2d3c09523d06ac2992de784dd9c59a7dd4f3751 (HEAD -> master, origin/master, origin/HEAD)
Author: David Moreau Simard <moi@dmsimard.com>
Date:   Wed Aug 19 23:17:46 2020 -0400

    CLI: Add '--long' to 'playbook list'
    
    We choose to exclude some columns by default and move them under
    '--long' in case there is a use case for them:
    
    - name won't always be set and so can be irrelevant
    - the amount of plays isn't as important as tasks, results and hosts
    - the amount of files and records isn't particularly critical
    
    Change-Id: Ia7a6a91973c9735140a6c2c9c691dac6ab7f7db2

commit 1b5bedb125a3c20e99dfba4278be0357cacb290e
Author: David Moreau Simard <moi@dmsimard.com>
Date:   Wed Aug 19 23:12:42 2020 -0400

    CLI: Add number of items in 'playbook list'
    
    This adds columns to display the number of plays, tasks, results, hosts,
    files and records in each playbook.
    
    Change-Id: If8416e43e81b11d3c22e0ec57fee2776951f9c41

commit a813ac38e3c62e1b36af1b364aca85fa82ee558e
Author: David Moreau Simard <moi@dmsimard.com>
Date:   Wed Aug 19 22:29:47 2020 -0400

    CLI: Add '--resolve' to 'ara result list'
    
    This translates IDs into human-readable identifiers.
    
    For performance purposes, we try to avoid querying for the same
    playbook, play, host or task more than once by using lru_cache.
    
    Change-Id: I2862bf6814ee17da2ee9d60b1af61eb5e4c9f4ec

commit 90a63a1825b0fb20ab9ee4ff03387458526226ad
Author: David Moreau Simard <moi@dmsimard.com>
Date:   Wed Aug 19 22:25:07 2020 -0400

    CLI: Add '--long' argument to ara result list
    
    We have to be opinionated about the columns we return by default because
    we do not have unlimited width to display data in.
    
    The 'changed' and 'ignore_errors' fields are somewhat combined into the
    status field that returns 'changed' or 'ignored' while the 'play' field
    is not necessarily required if the task and host context are present.

I suspect one of the above commits may lead to the errors I'm seeing.

**Comment by watsonb** [comment]
I'm trying to get this to work with `molecule`.  Here are the versions:

```bash
$ molecule --version
molecule 3.0.7
   ansible==2.9.12 python==3.8
```

As I alluded to previously, I used the ara_api Ansible role to throw an ARA API Server on a test machine earlier and had success with molecule and regular playbook runs.  Since the initial testing went well, I decided to run an honest server dedicated to ARA with more storage, etc.

From the machine running Ansible, I can get to the ARA Web page:

![image](https://user-images.githubusercontent.com/1863643/91038860-1dda6900-e5d1-11ea-9fa9-fb22d768be1d.png)

Here are some relevant ARA environment variables:

```bash
$ (venv3_ansible-2.9.12) ben@knedmhils042:~/workspace/kiewit/ansible/roles/ar_linux_kiewitplaza_cert$ printenv | grep ARA
ARA_DEBUG=True
ARA_API_SERVER=http://kneawxalp101.kiewitplaza.com
ARA_LOG_LEVEL=DEBUG
ARA_API_CLIENT=http
ARA_API_TIMEOUT=15
```

I just ran:

```bash
$ molecule --debug --base-config molecule/base_config_3x.yml verify > ~/molecule_out.txt

Failed to post on /api/v1/playbooks: {'ansible_version': '2.9.12', 'arguments': {'version': None, 'verbosity': 3, 'ask_pass': False, 'private_key_file': None, 'remote_user': None, 'connection': 'smart', 'timeout': 10, 'ssh_common_args': '', 'sftp_extra_args': '', 'scp_extra_args': '', 'ssh_extra_args': '', 'force_handlers': False, 'flush_cache': False, 'become': False, 'become_method': 'sudo', 'become_user': None, 'become_ask_pass': False, 'tags': ('all',), 'skip_tags': ('notest', 'molecule-notest'), 'check': False, 'syntax': False, 'diff': True, 'inventory': ('/home/ben/.cache/molecule/ar_linux_kiewitplaza_cert/default/inventory',), 'listhosts': False, 'subset': None, 'extra_vars': "Not saved by ARA as configured by 'ignored_arguments'", 'vault_ids': (), 'ask_vault_pass': False, 'vault_password_files': (), 'forks': 50, 'module_path': None, 'listtasks': False, 'listtags': False, 'step': False, 'start_at_task': None, 'args': ('/home/ben/workspace/kiewit/ansible/roles/ar_linux_kiewitplaza_cert/molecule/default/verify.yml',)}, 'status': 'running', 'path': '/home/ben/workspace/kiewit/ansible/roles/ar_linux_kiewitplaza_cert/molecule/default/verify.yml', 'started': '2020-08-24T06:09:04.685205'}
Failed to post on /api/v1/playbooks: {'ansible_version': '2.9.12', 'arguments': {'version': None, 'verbosity': 3, 'ask_pass': False, 'private_key_file': None, 'remote_user': None, 'connection': 'smart', 'timeout': 10, 'ssh_common_args': '', 'sftp_extra_args': '', 'scp_extra_args': '', 'ssh_extra_args': '', 'force_handlers': False, 'flush_cache': False, 'become': False, 'become_method': 'sudo', 'become_user': None, 'become_ask_pass': False, 'tags': ('all',), 'skip_tags': ('notest', 'molecule-notest'), 'check': False, 'syntax': False, 'diff': True, 'inventory': ('/home/ben/.cache/molecule/ar_linux_kiewitplaza_cert/default/inventory',), 'listhosts': False, 'subset': None, 'extra_vars': "Not saved by ARA as configured by 'ignored_arguments'", 'vault_ids': (), 'ask_vault_pass': False, 'vault_password_files': (), 'forks': 50, 'module_path': None, 'listtasks': False, 'listtags': False, 'step': False, 'start_at_task': None, 'args': ('/home/ben/workspace/kiewit/ansible/roles/ar_linux_kiewitplaza_cert/molecule/default/verify.yml',)}, 'status': 'running', 'path': '/home/ben/workspace/kiewit/ansible/roles/ar_linux_kiewitplaza_cert/molecule/default/verify.yml', 'started': '2020-08-24T06:09:04.685205'}
[WARNING]: Failure using method (v2_playbook_on_start) in callback plugin
(<ansible.plugins.callback.ara_default.CallbackModule object at
0x7f2ea51dec10>): Expecting value: line 1 column 1 (char 0)
[WARNING]: Failure using method (v2_playbook_on_play_start) in callback plugin
(<ansible.plugins.callback.ara_default.CallbackModule object at
0x7f2ea51dec10>): 'NoneType' object is not subscriptable
[WARNING]: Failure using method (v2_playbook_on_task_start) in callback plugin
(<ansible.plugins.callback.ara_default.CallbackModule object at
0x7f2ea51dec10>): 'NoneType' object is not subscriptable
[WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible.plugins.callback.ara_default.CallbackModule object at
0x7f2ea51dec10>): 'NoneType' object is not subscriptable
```

The rest of the output will be attached as molecule_out.txt once I sanitize it.

My ultimate goal is to have a functioning ARA API server capturing all Ansible content in our environment, be it a person running a playbook locally from their machine, Jenkins running molecule tests of our roles, or AWX/Tower running playbooks.  This way I can surface common errors and fix them.

Let me know if there is anything I should try on the server side to debug.  Since I use Ansible to make servers, I can easily re-create it if necessary.

Perhaps I can perform REST calls manually using a REST client to probe the server?  Let me know.

**Comment by watsonb** [comment]
Here are the relevant ara_api_* role variables I set when installing the server.  Everything else unspecified is the role default value.

```yaml
ara:
      hosts:
        kneawxalp101.kiewitplaza.com:  # ARA server
          ara_api_frontend_server: nginx
          ara_api_wsgi_server: gunicorn
          ara_api_fqdn: kneawxalp101.kiewitplaza.com
          ara_api_cors_origin_allow_all: true
          ara_api_root_dir: "/opt/ara"
          ara_api_allowed_hosts:
            - "127.0.0.1"
            - "localhost"
            - "::1"
            - "{{ ara_api_fqdn }}"
            - ".kiewittest.com"
            - ".kiewitplaza.com"
            - ".kiewit.com"
```

The only difference between this and my test server (that worked earlier) is the (obvious) fqdn and the (not so obvious) ara_api_root_dir.  On my test server, the root dir was in the ansible user's home directory and on this dedicated server, I created a dedicated disk/mount at /opt/ara for the server root.  I've verified that the mount is owned by the ansible user, that the systemd service is running without error, and as I mentioned before, I can get to the website just fine.

**Comment by watsonb** [comment]
aha!

```bash
$ journalctl -u ara-api

...

Aug 24 11:57:41 kneawxalp101.kiewitplaza.com gunicorn[4189]: Traceback (most recent call last):
Aug 24 11:57:41 kneawxalp101.kiewitplaza.com gunicorn[4189]:   File "/opt/ara/virtualenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
Aug 24 11:57:41 kneawxalp101.kiewitplaza.com gunicorn[4189]:     return self.cursor.execute(sql, params)
Aug 24 11:57:41 kneawxalp101.kiewitplaza.com gunicorn[4189]:   File "/opt/ara/virtualenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
Aug 24 11:57:41 kneawxalp101.kiewitplaza.com gunicorn[4189]:     return Database.Cursor.execute(self, query, params)
Aug 24 11:57:41 kneawxalp101.kiewitplaza.com gunicorn[4189]: sqlite3.OperationalError: attempt to write a readonly database

...
```

turns out ansible.sqlite was owned by root and therefore not writable by the user running the API server.  a litlte `chown` command and we're back in business!
