### ISSUE TITLE
1.5.0rc1: error 500 by callback on /api/v1/playbooks

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#174]
## What is the issue ?

I noticed this issue when running Ansible's integration tests [here](https://github.com/ansible/ansible/pull/57231).
Strangely, I didn't see this occur when testing kolla-ansible or openstack-ansible:

```
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]: 2020-09-19 21:11:40,083 ERROR django.request: Internal Server Error: /api/v1/playbooks
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]: Traceback (most recent call last):
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     return self.cursor.execute(sql, params)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     return self.cursor.execute(query, args)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     res = self._query(query)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     db.query(q)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/MySQLdb/connections.py", line 226, in query
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     _mysql.connection.query(self, query)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]: MySQLdb._exceptions.OperationalError: (1366, "Incorrect string value: '\\xC5\\x9A\\xC3\\x8C\\xCE\\xB2...' for column `ara`.`playbooks`.`path` at row 1")
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]: The above exception was the direct cause of the following exception:
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]: Traceback (most recent call last):
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     response = get_response(request)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     response = self.process_exception_by_middleware(e, request)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     return view_func(*args, **kwargs)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     return self.dispatch(request, *args, **kwargs)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     response = self.handle_exception(exc)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     self.raise_uncaught_exception(exc)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     raise exc
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     response = handler(request, *args, **kwargs)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/rest_framework/mixins.py", line 19, in create
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     self.perform_create(serializer)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/rest_framework/mixins.py", line 24, in perform_create
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     serializer.save()
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/rest_framework/serializers.py", line 213, in save
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     self.instance = self.create(validated_data)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/rest_framework/serializers.py", line 932, in create
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     instance = ModelClass._default_manager.create(**validated_data)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/models/query.py", line 422, in create
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     obj.save(force_insert=True, using=self.db)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/ara/api/models.py", line 51, in save
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     return super(Duration, self).save(*args, **kwargs)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/models/base.py", line 741, in save
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     force_update=force_update, update_fields=update_fields)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     force_update, using, update_fields,
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     using=using, raw=raw)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     return query.get_compiler(using=using).execute_sql(return_id)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     cursor.execute(sql, params)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     return executor(sql, params, many, context)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     return self.cursor.execute(sql, params)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     return self.cursor.execute(sql, params)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     return self.cursor.execute(query, args)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     res = self._query(query)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     db.query(q)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:   File "/home/fedora/.ara/virtualenv/lib64/python3.7/site-packages/MySQLdb/connections.py", line 226, in query
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]:     _mysql.connection.query(self, query)
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]: django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xC5\\x9A\\xC3\\x8C\\xCE\\xB2...' for column `ara`.`playbooks`.`path` at row 1")
Sep 19 21:11:40 trunk.demo.recordsansible.org gunicorn[29721]: 127.0.0.1 - - [19/Sep/2020:21:11:40 +0000] "POST /api/v1/playbooks HTTP/1.0" 500 27 "-" "ara-http-client_1.5.0.0rc1"
```
This could be a manifestation of the kind of issues we see with paths and funny characters in them: https://github.com/ansible-community/ara/issues/48

## What should be happening ?

It should work.

**Comment by dmsimard** [comment]
Yeah... paths with funny characters :(

From the perspective of the callback:
![Screenshot from 2020-09-19 17-26-21](https://user-images.githubusercontent.com/1291204/93689524-4e60d600-fa9d-11ea-8c12-f0a0119378ef.png)

I guess we should be able to reproduce the issue with an integration test and the ``-ÅÑŚÌβŁÈ/``string.

**Comment by dmsimard** [comment]
Ran a playbook with that path and it worked ¯\_(ツ)_/¯

![Screenshot from 2020-09-19 22-27-18](https://user-images.githubusercontent.com/1291204/93692939-63eaf580-fac7-11ea-90da-8679a328c847.png)

Need to investigate some more but I'm not considering this a blocker for 1.5.0.

**Comment by dmsimard** [comment]
Running a playbook from ``/tmp/-ÅÑŚÌβŁÈ/playbook.yml`` worked fine with sqlite and postgresql but raised the exception in the original bug report when using mysql.

There seems to be a certain amount of literature on this exception with MySQL including but not limited to:
- https://stackoverflow.com/questions/2108824/mysql-incorrect-string-value-error-when-save-unicode-string-in-django
- https://stackoverflow.com/questions/41918241/django-unable-to-save-unicode-string-in-mysql-operationalerror-1366-incorre
- https://stackoverflow.com/questions/63141740/django-db-utils-operationalerror-1366-incorrect-string-value-django-mysql

From the looks of it, we'd need to set:
```
# [...]
  DATABASE_ENGINE: django.db.backends.mysql
  DATABASE_OPTIONS:
    charset: "utf8mb4"
# [...]
```
And then make sure the database and tables are in the right charset.

In the case of our existing mysql database (for [api.demo.recordsansible.org](https://api.demo.recordsansible.org)) it was created with:
```
MariaDB [(none)]> show variables like 'char%';
+--------------------------+------------------------------+
| Variable_name            | Value                        |
+--------------------------+------------------------------+
| character_set_client     | utf8                         |
| character_set_connection | utf8                         |
| character_set_database   | latin1                       |
| character_set_filesystem | binary                       |
| character_set_results    | utf8                         |
| character_set_server     | latin1                       |
| character_set_system     | utf8                         |
| character_sets_dir       | /usr/share/mariadb/charsets/ |
+--------------------------+------------------------------+
8 rows in set (0.001 sec)
MariaDB [(none)]> show create database ara;
+----------+----------------------------------------------------------------+
| Database | Create Database                                                |
+----------+----------------------------------------------------------------+
| ara      | CREATE DATABASE `ara` /*!40100 DEFAULT CHARACTER SET latin1 */ |
+----------+----------------------------------------------------------------+
1 row in set (0.000 sec)
MariaDB [ara]> show create table playbooks;
+-----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table     | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
+-----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| playbooks | CREATE TABLE `playbooks` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created` datetime(6) NOT NULL,
  `updated` datetime(6) NOT NULL,
  `started` datetime(6) NOT NULL,
  `ended` datetime(6) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `ansible_version` varchar(255) NOT NULL,
  `status` varchar(25) NOT NULL,
  `arguments` longblob NOT NULL,
  `path` varchar(255) NOT NULL,
  `duration` bigint(20) DEFAULT NULL,
  `controller` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1703 DEFAULT CHARSET=latin1 |
+-----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)
```

I'll try changing the charset when I have a chance -- otherwise it sounds like a workaround would be to use postgresql or sqlite for now.

**Comment by dmsimard** [comment]
With mariadb-server-10.3.27 on centos8 I'm able to reproduce the issue using charset ``latin1`` and collation ``latin1_swedish_ci`` but it works fine using ``utf8`` as charset and ``utf8_general_ci`` as collation.

**Comment by dmsimard** [comment]
I wasn't able to figure out the right way to change the charset/collation on the database as well as the tables without causing a range of issues.

What seems to work is to use django to dump the data (instead of mysqldump) and then re-import it:
- run ``ara-manage dumpdata -o dump.json`` from the app where the database is in latin1
- create a new database with utf8/utf8_general_ci, run ``ara-manage migrate``
- run ``ara-manage loaddata dump.json``
