### ISSUE TITLE
package fails to build in fedora >= 33 due to mismatched versions of python-box and dynaconf

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#181]
## What is the issue ?

I've first seen this error when updating Fedora packages for 1.5.2, examples:
- rawhide/f34: https://koji.fedoraproject.org/koji/taskinfo?taskID=53971624
- f33: https://koji.fedoraproject.org/koji/taskinfo?taskID=53971710

```python
+ /usr/bin/python3 manage.py test ara
Creating test database for alias 'default'...
[ara] Using settings file: /builddir/.ara/server/settings.yaml
Traceback (most recent call last):
  File "/builddir/build/BUILD/ara-1.5.2/manage.py", line 22, in <module>
    main()
  File "/builddir/build/BUILD/ara-1.5.2/ara/server/__main__.py", line 58, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.9/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.9/site-packages/django/core/management/commands/test.py", line 53, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/lib/python3.9/site-packages/django/test/runner.py", line 684, in run_tests
    old_config = self.setup_databases(aliases=databases)
  File "/usr/lib/python3.9/site-packages/django/test/runner.py", line 604, in setup_databases
    return _setup_databases(
  File "/usr/lib/python3.9/site-packages/django/test/utils.py", line 169, in setup_databases
    connection.creation.create_test_db(
  File "/usr/lib/python3.9/site-packages/django/db/backends/base/creation.py", line 67, in create_test_db
    call_command(
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python3.9/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.9/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/lib/python3.9/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/lib/python3.9/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
    if self.has_table():
  File "/usr/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/db/backends/base/base.py", line 260, in cursor
    return self._cursor()
  File "/usr/lib/python3.9/site-packages/django/db/backends/base/base.py", line 236, in _cursor
    self.ensure_connection()
  File "/usr/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/usr/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 199, in get_new_connection
    conn = Database.connect(**conn_params)
TypeError: 'box_it_up' is an invalid keyword argument for this function
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.kgYrc8 (%check)
    Bad exit status from /var/tmp/rpm-tmp.kgYrc8 (%check)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/util.py", line 789, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/ara.spec
```

However it works on f32: https://koji.fedoraproject.org/koji/taskinfo?taskID=53971772

## What should be happening ?

I haven't yet investigated why this is happening but it should just work.

**Comment by dmsimard** [comment]
I tested with an updated scratch build of dynaconf 3.1.2 and it works fine: https://koji.fedoraproject.org/koji/taskinfo?taskID=54934653

I will build and tag updates.

**Comment by dmsimard** [comment]
rawhide (f34) was updated to 3.1.2: https://bodhi.fedoraproject.org/updates/FEDORA-2020-36df584695
dynaconf 3.1.2 update proposed to f33: https://bodhi.fedoraproject.org/updates/FEDORA-2020-ad83b2fda2

Now we need to wait until dynaconf 3.1.2 lands in f33 and then we should be able to build ara.

**Comment by dmsimard** [comment]
Doing a recheck with the updated dynaconf landed in f33/f34, everything is passing so far:
![Screenshot from 2020-11-19 09-40-31](https://user-images.githubusercontent.com/1291204/99680729-5f04dc80-2a4b-11eb-943e-e6e7064c3d9f.png)

I'll let the tests finish but we should be able to merge the PRs soon: https://src.fedoraproject.org/rpms/ara/pull-requests

**Comment by dmsimard** [comment]
Builds are out for testing: https://twitter.com/RecordsAnsible/status/1329489603112415232

I'll close this issue since it's fixed.
