### ISSUE TITLE
Missing "which" package in centos8 ara container

### ISSUE THREAD

**Issue by arrfab** [ansible-community/ara#192]
## What is the issue ?
When pulling latest container image from quay.io , it seems that now one needed package is missing, but needed by ara : 
```
Trying to pull quay.io/recordsansible/ara-api:centos8-pypi-latest...
Getting image source signatures
Copying blob 573ee0ede1f0 done
Copying blob 6d81fbe39a22 done
Copying config 36bbc76c5d done
Writing manifest to image destination
Storing signatures
7b57cd1b8e5037c52b1e2f281508133fb28c00adc6d05997c5a5b8939fc5ad47
```
## What should be happening ?
When calling some maintenance jobs (like pruning DB), it was working before but it doesn't anymore. example : 

```
podman exec -ti --tty ara-api-server  ara playbook prune --days 7 --limit 5000 --confirm 
Traceback (most recent call last):
  File "/usr/local/bin/ara", line 7, in <module>
    from ara.cli.base import main
  File "/usr/local/lib/python3.6/site-packages/ara/cli/base.py", line 9, in <module>
    from cliff.app import App
  File "/usr/local/lib/python3.6/site-packages/cliff/app.py", line 24, in <module>
    import cmd2
  File "/usr/local/lib/python3.6/site-packages/cmd2/__init__.py", line 30, in <module>
    from .cmd2 import Cmd
  File "/usr/local/lib/python3.6/site-packages/cmd2/cmd2.py", line 122, in <module>
    class Cmd(cmd.Cmd):
  File "/usr/local/lib/python3.6/site-packages/cmd2/cmd2.py", line 130, in Cmd
    DEFAULT_EDITOR = utils.find_editor()
  File "/usr/local/lib/python3.6/site-packages/cmd2/utils.py", line 385, in find_editor
    if which(editor):
  File "/usr/local/lib/python3.6/site-packages/cmd2/utils.py", line 201, in which
    exe_path = subprocess.check_output(['which', exe_name], stderr=subprocess.STDOUT).strip()
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'which': 'which'
Error: non zero exit code: 1: OCI runtime error
```
it seems pkg `which` is missing from base container so ideally just adding it to https://github.com/ansible-community/ara/blob/1b848c7c3617f7163a64113d4e2e0c76230a3e19/contrib/container-images/centos8-pypi.sh#L9 would make it work again.

To confirm, I just added it "manually" in container and then it works : 
```
podman exec -ti --tty ara-api-server dnf install -y which
podman exec -ti --tty ara-api-server  ara playbook prune --days 7 --limit 5000 --confirm
```

**Comment by dmsimard** [comment]
@arrfab o/ thanks for the issue

I sent a patch to add the missing ``which`` package (as well as other updates): https://review.opendev.org/c/recordsansible/ara/+/765638

If everything is good new images will be published with the fix included when it merges.
