### ISSUE TITLE
1.5.3: "sqlite3.OperationalError: database is locked" when recording playbook with the default offline client

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#195]
## What is the issue ?

@noonedeadpunk tipped me off to an issue that I was able to reproduce by running a simple small playbook in a loop with the callback enabled and the default offline API client. For reference, I put the full non-debug and debug logs in this gist: https://gist.github.com/dmsimard/70a080d5ab35d37c536f4f4d22189e7d

It would always fail at the beginning of the first play:
```
Operations to perform:
  Apply all migrations: admin, api, auth, contenttypes, db, sessions
Running migrations:
  No migrations to apply.
PLAY [apply cinder patch] ******************************************************
2020-12-04 03:09:06,424 INFO ansible: PLAY [apply cinder patch] ******************************************************
2020-12-04 03:09:06,449 ERROR django.request: Internal Server Error: /api/v1/playbooks/145
Traceback (most recent call last):
  File "/opt/ansible-runtime/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/ansible-runtime/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked
```

With ``ARA_DEBUG=true`` and ``ARA_LOG_LEVEL=DEBUG`` we have a bit more data about what's happening:
```
Operations to perform:
  Apply all migrations: admin, api, auth, contenttypes, db, sessions
Running migrations:
  No migrations to apply.
2020-12-04 03:02:37,191 DEBUG ara.plugins.callback.default: working with 1 thread(s)
2020-12-04 03:02:37,191 DEBUG ara.plugins.callback.default: v2_playbook_on_start
2020-12-04 03:02:37,191 DEBUG ara.plugins.callback.default: Ignoring argument: extra_vars
2020-12-04 03:02:37,192 DEBUG urllib3.connectionpool: Starting new HTTP connection (1): localhost:47597
2020-12-04 03:02:37,211 DEBUG urllib3.connectionpool: http://localhost:47597 "POST /api/v1/playbooks HTTP/1.1" 201 1127
2020-12-04 03:02:37,211 DEBUG ara.clients.http: HTTP 201: post on /api/v1/playbooks
2020-12-04 03:02:37,212 DEBUG ara.plugins.callback.default: File not in cache, getting or creating: /root/openstack-ansible/test-1.yml

PLAY [apply cinder patch] ******************************************************
2020-12-04 03:02:37,216 INFO ansible: PLAY [apply cinder patch] ******************************************************
2020-12-04 03:02:37,216 DEBUG ara.plugins.callback.default: v2_playbook_on_play_start
2020-12-04 03:02:37,216 DEBUG ara.plugins.callback.default: Updating playbook labels to match: check:False,tags:all
2020-12-04 03:02:37,218 DEBUG urllib3.connectionpool: Starting new HTTP connection (2): localhost:47597
2020-12-04 03:02:37,252 DEBUG urllib3.connectionpool: http://localhost:47597 "POST /api/v1/files HTTP/1.1" 201 1080
2020-12-04 03:02:37,253 DEBUG ara.clients.http: HTTP 201: post on /api/v1/files
Internal Server Error: /api/v1/playbooks/95
Traceback (most recent call last):
  File "/opt/ansible-runtime/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/ansible-runtime/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked
```

I am unable to reproduce the issue if we don't set any labels on the playbooks (with ``ARA_ARGUMENT_LABELS=""`` to avoid having any labels by default) so I can hazard a guess that it could have something to do with labels.

I am also unable to reproduce this with ara 1.5.1 which was the last release without threading.

Looking at the bigger picture, this operation is synchronous (not in a thread) while the things in it's general vicinity **are** threaded:
- https://github.com/ansible-community/ara/blob/1b848c7c3617f7163a64113d4e2e0c76230a3e19/ara/plugins/callback/ara_default.py#L303-L304
- https://github.com/ansible-community/ara/blob/1b848c7c3617f7163a64113d4e2e0c76230a3e19/ara/plugins/callback/ara_default.py#L427-L431

The threaded implementation looks problematic and needs more work.

## What should be happening ?

We didn't have this issue before the implementation of threading -- let's fix it :)

**Comment by ccamacho** [comment]
@dmsimard Im having another weird issue that might be related, when executing 4 playbooks, ara only takes gets the tasks from 2, all the other resources like the files are there but not the tasks logs.

**Comment by dmsimard** [comment]
Hey @ccamacho and thanks for reporting back -- could you confirm if you're also seeing this with the offline client ?

**Comment by ccamacho** [comment]
Indeed @dmsimard indeed, this error "sqlite3.OperationalError: database is locked" and also ara skipping to log the playbook tasks, everything worked fine 1.5.1

**Comment by dmsimard** [comment]
I've proposed a patch to disable threading by default: https://review.opendev.org/c/recordsansible/ara/+/767764
It effectively changes the default behavior to be the same as 1.5.1 but allows to enable threading by setting ``ARA_CALLBACK_THREADS``.

I've tested it locally and I am no longer able to reproduce this issue.

**Comment by dmsimard** [comment]
This will land in 1.5.4 that I am preparing for release early next week.
