### ISSUE TITLE
New dynaconf version (3.1.3) breaks ability to read ~/.ara/server/settings.yaml

### ISSUE THREAD

**Issue by marpy** [ansible-community/ara#212]
## What is the issue ?

`ara-manage migrate` throws an AttributeError exception with the latest dynaconf version
```
(ara) [mymachine ~]$ ara-manage migrate
[ara] No setting found for SECRET_KEY. Generating a random key...
Traceback (most recent call last):
  File "/home/build/ara/bin/ara-manage", line 8, in <module>
    sys.exit(main())
  File "/home/build/ara/lib/python3.6/site-packages/ara/server/__main__.py", line 41, in main
    if not os.path.exists(settings.ARA_SETTINGS):
  File "/home/build/ara/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/build/ara/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/build/ara/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/build/ara/lib/python3.6/site-packages/ara/server/settings.py", line 263, in <module>
    ALLOWED_HOSTS=ALLOWED_HOSTS.to_list(),
AttributeError: 'list' object has no attribute 'to_list'
```

## What should be happening ?
ara-manage migrate should successfully read the configuration file and proceed

**Comment by Rabieezz** [comment]
@marpy could you please tell me what version you used to overcome this ??

**Comment by dmsimard** [comment]
> @marpy could you please tell me what version you used to overcome this ??

@Rabieezz Until we figure out the issue you need to pin dynaconf to an earlier version for now, for example: https://review.opendev.org/c/openstack/openstack-ansible/+/779254/1/scripts/scripts-library.sh

**Comment by marpy** [comment]
Oops, I forgot to mention that. dynaconf 3.1.2 worked just fine. I pinned it in our requirements file as a stopgap.

**Comment by dmsimard** [comment]
FYI dynaconf already has a fix proposed for the regression: https://github.com/rochacbruno/dynaconf/pull/541

I've tested that it does resolve this issue and it will be released in dynaconf 3.1.4 soon.

**Comment by marpy** [comment]
Would it be useful to explicitly exclude 3.1.3 in the dependencies?

**Comment by dmsimard** [comment]
Sure. It's currently unpinned but we could set dynaconf in the [requirements](https://github.com/ansible-community/ara/blob/196b74bf82ecd45e99afe6c8d1d5224ffbb0524a/setup.cfg#L69) to something like ``>=3.0.0,!3.1.3,<4.0.0`` with a comment to this issue.

**Comment by marpy** [comment]
Nice! Thanks, @dmsimard!
