### ISSUE TITLE
Need a documentation on how to connect a Mysql database to ARA

### ISSUE THREAD

**Issue by Rabieezz** [ansible-community/ara#242]
## What is the issue ?
I need some explanation on how ARA can connect to a local mysql database, I followed the steps in the documentation but I still have some questions : 

When I create the database and i try to connect to it i have the following messages : 

 ```
~/.ara/server # ara-manage inspectdb --database /var/lib/mysql/ara/
[ara] Using settings file: /root/.ara/server/settings.yaml
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/db/utils.py", line 166, in ensure_defaults
    conn = self.databases[alias]
KeyError: '/var/lib/mysql/ara/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/bin/ara-manage", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.8/site-packages/ara/server/__main__.py", line 58, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/root/.local/lib/python3.8/site-packages/django/core/management/commands/inspectdb.py", line 34, in handle
    for line in self.handle_inspection(options):
  File "/root/.local/lib/python3.8/site-packages/django/core/management/commands/inspectdb.py", line 40, in handle_inspection
    connection = connections[options['database']]
  File "/root/.local/lib/python3.8/site-packages/django/db/utils.py", line 198, in __getitem__
    self.ensure_defaults(alias)
  File "/root/.local/lib/python3.8/site-packages/django/db/utils.py", line 168, in ensure_defaults
    raise ConnectionDoesNotExist("The connection %s doesn't exist" % alias)
django.db.utils.ConnectionDoesNotExist: The connection /var/lib/mysql/ara/ doesn't exist
```
Although the database exists and the path is the right one to me. So what am I missing here ?

the second question is does ARA create the tables needed when it connectes to the database or I need to run a script to create the right structure and set of tables nedded by ARA ? I don't understand this part and I would really appreciate any additional documentation that could help with that.

## What should be happening ?

ARA should connect to the database and run the server.

**Comment by Rabieezz** [comment]
@dmsimard I finally got what was blocking the run it was a copy/paste error in which I have put the path to the database instead of just putting the name of the database.
and actually I was about to ask you with ```ara-manage migrate --database ara ```  I should specify the name of my new database in order to synchronize it with the default one ?

**Comment by dmsimard** [comment]
There is no concept of synchronization between databases. If, for example, you are moving from a sqlite database to a mysql database, you'll be starting over from scratch.

All ``ara-manage migrate`` does is to create tables (if they don't already exist) and run SQL migrations (if they have not already been run). You don't need to specify ``--database ara``, there is only one database that can be configured at a time and it's the one you have in your ``settings.yaml`` file.

**Comment by Rabieezz** [comment]
Thank you so much for this insight very much appreciated.
