### ISSUE TITLE
ara_record: return active_client._instance() TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#325]
## What is the issue ?

I've seen the following trace happen twice on ubuntu bionic in CI (haven't seen it on fedora or centos):
```
TASK [smoke-tests : Record data with no type] **********************************
task path: /home/zuul/.ara-tests/git/ara/tests/integration/roles/smoke-tests/tasks/ara-ops.yaml:30
The full traceback is:
Traceback (most recent call last):
  File "/home/zuul/.ara-tests/virtualenv/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 147, in run
    res = self._execute()
  File "/home/zuul/.ara-tests/virtualenv/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 630, in _execute
    self._handler = self._get_action_handler(connection=self._connection, templar=templar)
  File "/home/zuul/.ara-tests/virtualenv/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 1086, in _get_action_handler
    collection_list=collections
  File "/home/zuul/.ara-tests/virtualenv/lib/python3.6/site-packages/ansible/plugins/loader.py", line 573, in get
    obj = obj(*args, **kwargs)
  File "/home/zuul/.ara-tests/virtualenv/lib/python3.6/site-packages/ara/plugins/action/ara_record.py", line 143, in __init__
    self.client = client_utils.active_client()
  File "/home/zuul/.ara-tests/virtualenv/lib/python3.6/site-packages/ara/clients/utils.py", line 50, in active_client
    return active_client._instance()
TypeError: 'NoneType' object is not callable
fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

I re-ran the job and it did not reproduce so it may be a race condition or something else ? ¯\\_(ツ)_/¯

Reading the trace, it looks like ara_record is not able to retrieve the (default offline) API client instanciated by the callback.
This has been working well as long as I remember and this exception is news to me... worth investigating :)

## What should be happening ?

The intent is for the callback to initialize the client since it has readily access to all the configuration variables and then for ara_record to recover the client instance and use it.

This allows ara_record to know how to communicate with the ARA API endpoint automagically without needing to specify configuration or credentials.

**Comment by dmsimard** [comment]
Links to failed jobs that detected the issue:
- https://dashboard.zuul.ansible.com/t/ansible/build/2217688d7b734bbb8059b9f252f7b1bb
- https://dashboard.zuul.ansible.com/t/ansible/build/a33aae7243504f0b887a786ab60ef547

**Comment by dmsimard** [comment]
The issue was caused by an outdated version of mariadb development libraries (via the ``libmariadb-dev`` package).
MySQL users on 18.04 should install ``libmariadbclient-dev`` instead before installing mysqlclient from pip.
