### ISSUE TITLE
Can't use ARA with python3.5

### ISSUE THREAD

**Issue by DataHearth** [ansible-community/ara#370]
## What is the issue ?

When running ARA with `python3.5`, after playing any playbook, you'll get an error `invalid syntax (base.py, line 143)`.

I've tested with `python3.8` and it's working as intended

**Steps to reproduce:**
```bash
docker run -it --rm python:3.5 bash
python3 -m venv /tmp/ara
source /tmp/ara/bin/activate
pip install --upgrade pip
pip install ansible ara[server]
export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)"
ansible-playbook some-play.yml
ara playbook list
```

playbook:
```yaml
- name: Demo playbook
  hosts: localhost
  tasks:
    - name: Hello world
      debug:
        msg: Hello, World!
```

Ansible verbose logs:
```bash
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller
starting with Ansible 2.12. Current version: 3.5.10 (default, Sep 10 2020, 18:30:47)
[GCC 8.3.0]. This feature will be removed from ansible-core in version 2.12.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
/tmp/ara2/lib/python3.5/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography.exceptions import InvalidSignature
ansible-playbook [core 2.11.9]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/ara2/lib/python3.5/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /tmp/ara2/bin/ansible-playbook
  python version = 3.5.10 (default, Sep 10 2020, 18:30:47) [GCC 8.3.0]
  jinja version = 2.11.3
  libyaml = True
No config file found; using defaults
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the
implicit localhost does not match 'all'
[WARNING]: Skipping plugin (/ara/ara/plugins/callback/ara_default.py) as it seems to be
invalid: No module named 'ara'
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: demo-playbook.yml ************************************************************
1 plays in demo-playbook.yml

PLAY [Demo playbook] *******************************************************************

TASK [Gathering Facts] *****************************************************************
task path: /ara/demo-playbook.yml:1
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1647731076.4867663-637-57623046258319 `" && echo ansible-tmp-1647731076.4867663-637-57623046258319="` echo /root/.ansible/tmp/ansible-tmp-1647731076.4867663-637-57623046258319 `" ) && sleep 0'
Using module file /tmp/ara2/lib/python3.5/site-packages/ansible/modules/setup.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-630g25hgw5a/tmpvpguvpbs TO /root/.ansible/tmp/ansible-tmp-1647731076.4867663-637-57623046258319/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1647731076.4867663-637-57623046258319/ /root/.ansible/tmp/ansible-tmp-1647731076.4867663-637-57623046258319/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/tmp/ara2/bin/python3 /root/.ansible/tmp/ansible-tmp-1647731076.4867663-637-57623046258319/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1647731076.4867663-637-57623046258319/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Hello world] *********************************************************************
task path: /ara/demo-playbook.yml:4
ok: [localhost] => {
    "msg": "Hello, World!"
}
META: ran handlers
META: ran handlers

PLAY RECAP *****************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

## What should be happening ?

Running ARA should not produce an error related to invalid syntax and in steps above, it should not fail at all, plus it should returns a valid output.

**Comment by dmsimard** [comment]
I've reproduced the issue with the error ``[WARNING]: Skipping callback 'ara_default', unable to load due to: invalid syntax (base.py, line 143)``.

It doesn't provide a traceback even with ``ansible-playbook -vvvv`` though...

The error comes from here: https://github.com/ansible/ansible/blob/8dfe4acba47948e8d6daa2219817e2ac89f26845/lib/ansible/executor/task_queue_manager.py#L222-L238

I set myself a break point with ``import pdb; pdb.set_trace()`` and got the following:
```
> /usr/local/lib/python3.5/site-packages/ansible/executor/task_queue_manager.py(238)load_callbacks()
-> display.warning("Skipping callback '%s', unable to load due to: %s" % (callback_name, to_native(e)))
(Pdb) callback_obj
<ansible.plugins.callback.ara_default.CallbackModule object at 0x7f2feba381d0>
(Pdb) callback_obj.__dict__
{'stats': None, '_plugin_options': {'default_labels': [], 'ignored_facts': ['ansible_env'], 'ignored_arguments': ['extra_vars'], 'api_timeout': 30, 'ignored_files': [], 'api_username': None, 'api_insecure': False, 'api_client': 'offline', 'api_server': 'http://127.0.0.1:8000', 'argument_labels': ['remote_user', 'check', 'tags', 'skip_tags', 'subset'], 'callback_threads': 0, 'api_password': None}, '_hide_in_debug': ('changed', 'failed', 'skipped', 'invocation', 'skip_reason'), 'delegation_cache': {}, 'ignored_files': [], 'result_started': {}, 'log': <logging.Logger object at 0x7f2feba38320>, 'disabled': False, 'task_cache': {}, 'host_cache': {}, 'result': None, 'result_ended': {}, 'file_cache': {}, 'client': None, 'task': None, 'default_labels': [], 'ignored_facts': ['ansible_env'], '_display': <ansible.utils.display.Display object at 0x7f2fee845c88>, 'wants_implicit_tasks': False, 'playbook': None, 'play': None, 'ignored_arguments': ['extra_vars'], 'argument_labels': ['remote_user', 'check', 'tags', 'skip_tags', 'subset'], 'callback_threads': None}
(Pdb) e
SyntaxError('invalid syntax', ('/usr/local/lib/python3.5/site-packages/dynaconf/base.py', 143, 44, '            if f"{key.upper()}_FOR_DYNACONF" in for_dynaconf_keys\n'))
```

When quitting pdb, I actually got the full trace:
```
ERROR! Unexpected Exception, this is probably a bug: 
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/ansible/executor/task_queue_manager.py", line 229, in load_callbacks
    callback_obj.set_options()
  File "/usr/local/lib/python3.5/site-packages/ara/plugins/callback/ara_default.py", line 232, in set_options
    verify=False if insecure else True,
  File "/usr/local/lib/python3.5/site-packages/ara/clients/utils.py", line 40, in get_client
    return AraOfflineClient(auth=auth, run_sql_migrations=run_sql_migrations)
  File "/usr/local/lib/python3.5/site-packages/ara/clients/offline.py", line 46, in __init__
    execute_from_command_line(["django", "migrate"])
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/site-packages/ara/server/settings.py", line 24, in <module>
    from dynaconf import LazySettings
  File "/usr/local/lib/python3.5/site-packages/dynaconf/__init__.py", line 1, in <module>
    from dynaconf.base import LazySettings  # noqa
  File "/usr/local/lib/python3.5/site-packages/dynaconf/base.py", line 143
    if f"{key.upper()}_FOR_DYNACONF" in for_dynaconf_keys
                                   ^
SyntaxError: invalid syntax
```

The error comes from trying to use an f-string which were implemented in python 3.6.

It turns out that the latest version of dynaconf requires python >= 3.7: https://github.com/rochacbruno/dynaconf/blob/e268152dbf9756272b05c31bc620b65cc8a36951/setup.py#L84

I ran out of time to continue looking for now but we should find out which version of dynaconf still works with 3.5 -- if it's too old or breaks other things, maybe we can consider other options like pinning for different versions of python (like [this](https://github.com/openstack/requirements/blob/2f2467ad1508f4b125fc3f15c9454dc711baca01/global-requirements.txt#L165-L166)).

We can also consider dropping support for 3.5 but I'd like to keep it for a while if it's not too much of a burden.

**Comment by dmsimard** [comment]
It works with python3.5 when installing the latest version of dynaconf 2.x (instead of the current 3.x) which is 2.2.3.
Installing 3.0.0 onwards fails so they've probably dropped support for it at that point.

We can pin it to ``dynaconf<3.0.0`` for python3.5 like the example I provided earlier, perhaps:
https://github.com/ansible-community/ara/blob/ca94ff4afaeccdbd3479c43cedac30a5c413ba1e/setup.cfg#L63-L73

**Comment by dmsimard** [comment]
> We can pin it to `dynaconf<3.0.0` for python3.5 like the example I provided earlier, perhaps:

Yes, yes, I think I want to do that: we'll be [updating django to 3.2](https://github.com/ansible-community/ara/pull/360) soon and django 3.2 supports py36 onwards -- effectively ending support for py35.

So the upcoming ara 1.5.8 release would still run on 3.5 and we'll drop support for it when we bump django in the next (major?) release. I must note the python 3.5 EOL notice:
```
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
```
