### ISSUE TITLE
ara package in fedora: f36 and rawhide broken due to out of date django-health-check

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#384]
## What is the issue ?

The version of django that is currently in Fedora rawhide and will ship in Fedora 36 (4.0.2) is too new and breaks things:
```
+ /usr/bin/python3 manage.py test ara
Creating test database for alias 'default'...
[ara] Server's LOGGING configuration has a 'root' logger which is deprecated after version 1.5.8 due to conflicts. Please update your settings.yaml or generate a new one by removing it from ara's configuration folder
[ara] Using settings file: /builddir/.ara/server/settings.yaml
Found 169 test(s).
Destroying test database for alias 'default'...
Traceback (most recent call last):
  File "/builddir/build/BUILD/ara-1.5.8/manage.py", line 22, in <module>
    main()
  File "/builddir/build/BUILD/ara-1.5.8/ara/server/__main__.py", line 66, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.10/site-packages/django/core/management/commands/test.py", line 24, in run_from_argv
    super().run_from_argv(argv)
  File "/usr/lib/python3.10/site-packages/django/core/management/base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.10/site-packages/django/core/management/base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.10/site-packages/django/core/management/commands/test.py", line 59, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/lib/python3.10/site-packages/django/test/runner.py", line 933, in run_tests
    self.run_checks(databases)
  File "/usr/lib/python3.10/site-packages/django/test/runner.py", line 852, in run_checks
    call_command('check', verbosity=self.verbosity, databases=databases)
  File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 187, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python3.10/site-packages/django/core/management/base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.10/site-packages/django/core/management/commands/check.py", line 63, in handle
    self.check(
  File "/usr/lib/python3.10/site-packages/django/core/management/base.py", line 438, in check
    all_issues = checks.run_checks(
  File "/usr/lib/python3.10/site-packages/django/core/checks/registry.py", line 77, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/lib/python3.10/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python3.10/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/lib/python3.10/site-packages/django/urls/resolvers.py", line 448, in check
    for pattern in self.url_patterns:
  File "/usr/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3.10/site-packages/django/urls/resolvers.py", line 634, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3.10/site-packages/django/urls/resolvers.py", line 627, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/builddir/build/BUILD/ara-1.5.8/ara/server/urls.py", line 46, in <module>
    path("healthcheck/", include("health_check.urls")),
  File "/usr/lib/python3.10/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/health_check/urls.py", line 1, in <module>
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (/usr/lib/python3.10/site-packages/django/conf/urls/__init__.py)
```

We're bumping from django 2.2 to 3.2 but we haven't yet looked into making it work with django 4.x.

## What should be happening ?

Maybe it's a small fix that we can do to make it compatible with both 3.2 and 4.x, maybe it's not.

**Comment by dmsimard** [comment]
Oh, I didn't pay attention to the traceback at all.

It's actually coming from django-healthcheck:
```
  File "/usr/lib/python3.10/site-packages/health_check/urls.py", line 1, in <module>
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (/usr/lib/python3.10/site-packages/django/conf/urls/__init__.py)
```

This has been fixed upstream (in https://github.com/KristianOellegaard/django-health-check/commit/93e9cdd1e881f255166df2d1189fcae838a077a9) but it turns out [python-django-health-check]([python-django-health-check](https://koji.fedoraproject.org/koji/packageinfo?packageID=30161)) is a bit out of date in Fedora and it turns out I'm the maintainer for that package.. oops.

I'll fix that.

**Comment by dmsimard** [comment]
Yeah, fixed it by updating python-django-health-check: https://koji.fedoraproject.org/koji/taskinfo?taskID=85302191

Not related to ara, closing the issue.

**Comment by dmsimard** [comment]
Just following up to wrap up, the update has been submitted to stable repos for rawhide and f36:
- https://bodhi.fedoraproject.org/updates/FEDORA-2022-6263f2df2b
- https://bodhi.fedoraproject.org/updates/FEDORA-2022-c1ed9a5a4a
