### ISSUE TITLE
Internal Server Error in browser

### ISSUE THREAD

**Issue by biohazd** [ansible-community/ara#40]
I often get the error in the browser "Internal Server Error".  If I view the other pages in the browser, they load fine, so its only 1 page that has the issue. e.g. https://ara/reports/list/4.html

[ root@ara-20:~]$ pip list
ansible (2.3.2.0)
ara (0.13.0)

Should i just upgrade ARA version, or is this a known issue?

The error logs show
```
[2019-05-09 13:20:24,624] ERROR in app: Exception on /reports/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/ara/views/reports.py", line 66, in report_list
    stats=stats)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/ara/templates/report_list.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/usr/local/lib/python2.7/site-packages/ara/templates/layout.html", line 6, in top-level template code
    {% block content -%}
  File "/usr/local/lib/python2.7/site-packages/ara/templates/report_list.html", line 10, in block "content"
    {% include "report.html" -%}
  File "/usr/local/lib/python2.7/site-packages/ara/templates/report.html", line 22, in top-level template code
    <a href="#" data-toggle="modal" data-target="#file_modal" data-load="{{ playbook.file.id }}/" title="{{ playbook.path }}">{{ playbook.path | basename }}</a>
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/usr/local/lib/python2.7/site-packages/ara/models.py", line 195, in file
    .filter(File.is_playbook)).one()
  File "/usr/local/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2953, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
[pid: 20661|app: 0|req: 228290/228300] 10.6.0.18 () {54 vars in 892 bytes} [Thu May  9 13:20:24 2019] GET /reports/ => generated 291 bytes in 413 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
```

**Comment by dmsimard** [comment]
@biohazd I believe the bug you are hitting was fixed with https://github.com/ansible-community/ara/commit/d69b2d34c20137eceffc3f5182541da4379f12b2 which landed in 0.16.

In any case, I would recommend using the latest version of ARA to benefit from the bug fixes and performance improvements over time.

Also note that Ansible 2.3 has been EOL since [2017-12-20](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html). I would also recommend updating Ansible to make sure you are not running with unpatched security vulnerabilities.

**Comment by biohazd** [comment]
Thanks for replying, I will try an upgrade.

**Comment by dmsimard** [comment]
@biohazd great, I'll close this for now -- please feel free to re-open if you encounter the issue with the latest versions.
