### ISSUE TITLE
ValueError: Incorrect timezone setting: local

### ISSUE THREAD

**Issue by hille721** [ansible-community/ara#401]
```
$ ara-manage migrate
Traceback (most recent call last):
  File "/home/hille/gitrepos/ara/.tox/ansible-integration/bin/ara-manage", line 10, in <module>
    sys.exit(main())
  File "/home/hille/gitrepos/ara/ara/server/__main__.py", line 27, in main
    if not os.path.exists(settings.ARA_SETTINGS):
  File "/home/hille/gitrepos/ara/.tox/ansible-integration/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/hille/gitrepos/ara/.tox/ansible-integration/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/hille/gitrepos/ara/.tox/ansible-integration/lib/python3.9/site-packages/django/conf/__init__.py", line 206, in __init__
    raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
ValueError: Incorrect timezone setting: local
```

## What is the issue ?
ara-manage migrate will lead to above Django error. Problem is in line https://github.com/ansible-community/ara/blob/master/ara/server/settings.py#L202 the expression `tzlocal.get_localzone().zone`, which results in `local` instead of `Europe/Berlin`.

My timezone is set via `TZ` environment variable:

```
$ echo $TZ
/usr/share/zoneinfo/Europe/Berlin
```

**Comment by hille721** [comment]
seems to be introduced in 8ce14cb84119f032f18a1aa189e1946107676b71 after discussion in #65

**Comment by dmsimard** [comment]
Thanks for reporting the issue, I haven't run into this one before.

Timezones are hard.

**Comment by hille721** [comment]
yes, was already looking how to fix this, but no success.

**Comment by dmsimard** [comment]
Looks like this issue has shown up in the [container CI job](https://ansible.softwarefactory-project.io/zuul/build/f41f6519b9e34fe0b49fe7ec8a674629/logs) (logs [here](https://1a846e8cdfbfe4342757-02fac59c71fd966508f1bee49d379c34.ssl.cf5.rackcdn.com/404/fc84dfd5d8b82add3477c9c51a63601448a4cb86/check/ara-container-images/f41f651/job-output.txt)).

It works for Fedora but fails on CentOS, perhaps a hint to investigate and troubleshoot later.

**Comment by dmsimard** [comment]
I'm not sure how we should resolve this yet but one thing to consider would be to update the tzlocal dependency. It's not impossible that we are running into a bug that has since been fixed.

We pinned it to ``<3.0`` a while back: https://github.com/ansible-community/ara/pull/258/commits/15d961f37c7f4b1fa8257265d5cb0ca5e934a276

Back then 3.0 was a pre-release and they're up to 4.x now:
![Screenshot from 2022-08-06 13-13-51](https://user-images.githubusercontent.com/1291204/183259137-50578d7d-293c-4efa-a476-2d39e0b852ed.png)

**Comment by dmsimard** [comment]
I've tried updating tzlocal to the latest release, it only required a little adjustment in the settings: https://github.com/ansible-community/ara/pull/404/commits/db8e5017255fd9b6d4eb05b4bb2b2144ea5896bc

It worked locally but let's find out if it resolves the issue I saw in CI.

**Comment by dmsimard** [comment]
I can reproduce the 'local' issue with CentOS 9 but not with CentOS 8.

I haven't yet tested if the tzlocal update fixes the CentOS 9 case since the image builds off of PyPI, not from source.

**Comment by dmsimard** [comment]
There is something else going on.

I've briefly reproduced the issue in a simplified way:
centos9:
```
> podman run -it quay.io/centos/centos:stream9 bash
[root@0d09dd13b73b /]# dnf -y install python3-pip
[root@0d09dd13b73b /]# pip install tzlocal
[root@0d09dd13b73b /]# python3
Python 3.9.13 (main, Jun  9 2022, 00:00:00) 
[GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tzlocal
>>> tzlocal.get_localzone_name()
>>> 
# ^ None (or 'local' in previous versions of tzlocal
```

centos8:
```
> podman run -it quay.io/centos/centos:stream8 bash
[root@d7e152b71d82 /]# dnf install python3-pip
[root@d7e152b71d82 /]# python3 -m pip install tzlocal
[root@d7e152b71d82 /]# python3
Python 3.6.8 (default, Oct 19 2021, 05:14:06) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tzlocal
>>> tzlocal.get_localzone_name()
'UTC'
```

**Comment by hille721** [comment]
can verify, with the changes you did in #404, my issue is solved (y)

**Comment by dmsimard** [comment]
Thanks for checking @hille721 !

I'm not convinced it's the right fix but it will help mitigate the issue until we can find out what's the root cause based on the reproducer I provided in my previous comment.

**Comment by hille721** [comment]
Why do you think it is not the right fix. 

For me the function is working now:

```
Python 3.9.5 (default, Nov 23 2021, 15:27:38)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tzlocal
>>> tzlocal.get_localzone_name()
'Europe/Berlin'
```

While the old `get_localzone().zone` was always returning `local`.

From my side we can also close this issue now.

**Comment by dmsimard** [comment]
> Why do you think it is not the right fix.

@hille721 I mean to say that it doesn't reproduce everywhere (i.e, on centos but not on fedora) and I have not determined the root cause as to why and finding the root cause may lead to a different fix.
