### ISSUE TITLE
container-images CI job suddenly failing with Connection refused when testing image builds

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#406]
## What is the issue ?

The ara-container-images job has suddenly started consistently failing: https://ansible.softwarefactory-project.io/zuul/builds?job_name=ara-container-images&skip=0

![Screenshot from 2022-08-05 16-44-47](https://user-images.githubusercontent.com/1291204/183160342-caaa0d4e-4a5f-4970-a2c1-580d8041bf0d.png)

Some logs:

```
2022-08-05 16:38:11.438194 | TASK [Build localhost/ara-api:fedora35-source-latest with fedora-source.sh]
2022-08-05 16:38:11.792480 | fedora-36 | +++ dirname /home/zuul-worker/src/github.com/ansible-community/ara/contrib/container-images/fedora-source.sh
2022-08-05 16:38:11.794549 | fedora-36 | ++ cd /home/zuul-worker/src/github.com/ansible-community/ara/contrib/container-images
# ...
2022-08-05 16:39:16.004294 | fedora-36 | + buildah config --env ARA_BASE_DIR=/opt/ara fedora-working-container
2022-08-05 16:39:16.069974 | fedora-36 | + buildah config --cmd 'bash -c '\''/usr/local/bin/ara-manage migrate && /usr/bin/gunicorn-3 --workers=4 --access-logfile - --bind 0.0.0.0:8000 ara.server.wsgi'\''' fedora-working-container
2022-08-05 16:39:16.136068 | fedora-36 | + buildah config --port 8000 fedora-working-container
2022-08-05 16:39:16.202359 | fedora-36 | + buildah commit fedora-working-container localhost/ara-api:fedora35-source-latest
2022-08-05 16:39:17.267884 | fedora-36 | Getting image source signatures
2022-08-05 16:39:17.268497 | fedora-36 | Copying blob sha256:bed35f21a436df75dbcd6e18a7552084e9a4dd15ee0fb3dfc0bc82d1b73a7586
2022-08-05 16:39:17.268782 | fedora-36 | Copying blob sha256:e55023378e18fdd3329296df3655533630fa9b7dab5228b0549c826ac6126c6e
2022-08-05 16:39:20.893704 | fedora-36 | Copying config sha256:f5550890a0801ef52bbde176613e186eb056208c80492a561f2677918039bc28
2022-08-05 16:39:20.915395 | fedora-36 | Writing manifest to image destination
2022-08-05 16:39:20.915541 | fedora-36 | Storing signatures
2022-08-05 16:39:20.981537 | fedora-36 | f5550890a0801ef52bbde176613e186eb056208c80492a561f2677918039bc28
2022-08-05 16:39:21.047292 | fedora-36 | ok: Runtime: 0:01:09.199481
2022-08-05 16:39:21.085260 | 
2022-08-05 16:39:21.085402 | TASK [Start localhost/ara-api:fedora35-source-latest with podman]
2022-08-05 16:39:21.646483 | fedora-36 | ce799dde236d07b4acf63a87328c348e7b9ca1d9c0a9b52cf8c90a7ab36b8f87
2022-08-05 16:39:22.118074 | fedora-36 | ok: Runtime: 0:00:00.383314
2022-08-05 16:39:22.139681 | 
2022-08-05 16:39:22.139819 | TASK [Get the API root]
2022-08-05 16:39:39.121706 | fedora-36 | ERROR
2022-08-05 16:39:39.121935 | fedora-36 | {
2022-08-05 16:39:39.121974 | fedora-36 |   "attempts": 3,
2022-08-05 16:39:39.122002 | fedora-36 |   "content": "",
2022-08-05 16:39:39.122027 | fedora-36 |   "elapsed": 0,
2022-08-05 16:39:39.122050 | fedora-36 |   "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>",
2022-08-05 16:39:39.122084 | fedora-36 |   "redirected": false,
2022-08-05 16:39:39.122109 | fedora-36 |   "status": -1,
2022-08-05 16:39:39.122131 | fedora-36 |   "url": "http://127.0.0.1:8000/api/"
2022-08-05 16:39:39.122154 | fedora-36 | }
```

buildah builds the image successfully and podman starts the container but it doesn't stay up and the test to check the API root fails.

In the container logs we have:
```
2022-08-05T18:05:58.993376000Z [ara] No setting found for SECRET_KEY. Generating a random key...
2022-08-05T18:05:59.017653000Z [ara] Writing default settings to /opt/ara/settings.yaml
2022-08-05T18:05:59.024114000Z [ara] Using settings file: /opt/ara/settings.yaml
2022-08-05T18:05:59.326325000Z [36;1mOperations to perform:[0m
2022-08-05T18:05:59.326506000Z [1m  Apply all migrations: [0madmin, api, auth, contenttypes, db, sessions
2022-08-05T18:05:59.326793000Z [36;1mRunning migrations:[0m
2022-08-05T18:05:59.345028000Z   Applying contenttypes.0001_initial...[32;1m OK[0m
2022-08-05T18:05:59.374252000Z   Applying auth.0001_initial...[32;1m OK[0m
2022-08-05T18:05:59.397401000Z   Applying admin.0001_initial...[32;1m OK[0m
2022-08-05T18:05:59.417649000Z   Applying admin.0002_logentry_remove_auto_add...[32;1m OK[0m
2022-08-05T18:05:59.436480000Z   Applying admin.0003_logentry_add_action_flag_choices...[32;1m OK[0m
2022-08-05T18:05:59.525512000Z   Applying api.0001_initial...[32;1m OK[0m
2022-08-05T18:05:59.559202000Z   Applying api.0002_remove_host_alias...[32;1m OK[0m
2022-08-05T18:05:59.591074000Z   Applying api.0003_add_missing_result_properties...[32;1m OK[0m
2022-08-05T18:05:59.681077000Z   Applying api.0004_duration_in_database...[32;1m OK[0m
2022-08-05T18:05:59.703813000Z   Applying api.0005_unique_label_names...[32;1m OK[0m
2022-08-05T18:05:59.728285000Z   Applying api.0006_remove_result_statuses...[32;1m OK[0m
2022-08-05T18:05:59.770709000Z   Applying api.0007_add_expired_status...[32;1m OK[0m
2022-08-05T18:05:59.786273000Z   Applying api.0008_playbook_controller...[32;1m OK[0m
2022-08-05T18:05:59.818656000Z   Applying api.0009_latesthost...[32;1m OK[0m
2022-08-05T18:05:59.840738000Z   Applying api.0010_result_delegated_to...[32;1m OK[0m
2022-08-05T18:05:59.870037000Z   Applying api.0011_play_label_name_max_length...[32;1m OK[0m
2022-08-05T18:05:59.906206000Z   Applying contenttypes.0002_remove_content_type_name...[32;1m OK[0m
2022-08-05T18:05:59.925664000Z   Applying auth.0002_alter_permission_name_max_length...[32;1m OK[0m
2022-08-05T18:05:59.941880000Z   Applying auth.0003_alter_user_email_max_length...[32;1m OK[0m
2022-08-05T18:05:59.955196000Z   Applying auth.0004_alter_user_username_opts...[32;1m OK[0m
2022-08-05T18:05:59.976346000Z   Applying auth.0005_alter_user_last_login_null...[32;1m OK[0m
2022-08-05T18:05:59.986304000Z   Applying auth.0006_require_contenttypes_0002...[32;1m OK[0m
2022-08-05T18:05:59.999692000Z   Applying auth.0007_alter_validators_add_error_messages...[32;1m OK[0m
2022-08-05T18:06:00.019473000Z   Applying auth.0008_alter_user_username_max_length...[32;1m OK[0m
2022-08-05T18:06:00.038854000Z   Applying auth.0009_alter_user_last_name_max_length...[32;1m OK[0m
2022-08-05T18:06:00.061527000Z   Applying auth.0010_alter_group_name_max_length...[32;1m OK[0m
2022-08-05T18:06:00.089663000Z   Applying auth.0011_update_proxy_permissions...[32;1m OK[0m
2022-08-05T18:06:00.109281000Z   Applying auth.0012_alter_user_first_name_max_length...[32;1m OK[0m
2022-08-05T18:06:00.120943000Z   Applying db.0001_initial...[32;1m OK[0m
2022-08-05T18:06:00.137945000Z   Applying sessions.0001_initial...[32;1m OK[0m
2022-08-05T18:06:00.602903000Z [2022-08-05 18:06:00 +0000] [1] [INFO] Starting gunicorn 20.1.0
2022-08-05T18:06:00.603541000Z [2022-08-05 18:06:00 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
2022-08-05T18:06:00.603726000Z [2022-08-05 18:06:00 +0000] [1] [INFO] Using worker: sync
2022-08-05T18:06:00.606754000Z [2022-08-05 18:06:00 +0000] [3] [INFO] Booting worker with pid: 3
2022-08-05T18:06:00.610745000Z [2022-08-05 18:06:00 +0000] [3] [ERROR] Exception in worker process
2022-08-05T18:06:00.610825000Z Traceback (most recent call last):
2022-08-05T18:06:00.610888000Z   File "/usr/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2022-08-05T18:06:00.610972000Z     worker.init_process()
2022-08-05T18:06:00.611035000Z   File "/usr/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2022-08-05T18:06:00.611111000Z     self.load_wsgi()
2022-08-05T18:06:00.611193000Z   File "/usr/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2022-08-05T18:06:00.611265000Z     self.wsgi = self.app.wsgi()
2022-08-05T18:06:00.611335000Z   File "/usr/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2022-08-05T18:06:00.611401000Z     self.callable = self.load()
2022-08-05T18:06:00.611457000Z   File "/usr/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2022-08-05T18:06:00.611522000Z     return self.load_wsgiapp()
2022-08-05T18:06:00.611582000Z   File "/usr/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2022-08-05T18:06:00.611646000Z     return util.import_app(self.app_uri)
2022-08-05T18:06:00.611713000Z   File "/usr/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
2022-08-05T18:06:00.611778000Z     mod = importlib.import_module(module)
2022-08-05T18:06:00.611839000Z   File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
2022-08-05T18:06:00.611902000Z     return _bootstrap._gcd_import(name[level:], package, level)
2022-08-05T18:06:00.612010000Z   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-08-05T18:06:00.612076000Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-08-05T18:06:00.612135000Z   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
2022-08-05T18:06:00.612197000Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-08-05T18:06:00.612264000Z   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-08-05T18:06:00.612329000Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-08-05T18:06:00.612386000Z   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
2022-08-05T18:06:00.612445000Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-08-05T18:06:00.612499000Z   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-08-05T18:06:00.612557000Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-08-05T18:06:00.612609000Z   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
2022-08-05T18:06:00.612680000Z ModuleNotFoundError: No module named 'ara'
```

Something might have changed in how the PYTHONPATH (or some similar config) is set up in the image because we mix packages from the distro and pip: https://github.com/ansible-community/ara/blob/5a984ad869ea0ab99de4c6c6b81590aa760e05cc/contrib/container-images/fedora-source.sh#L20-L22

gunicorn is installed from the distro while ara is installed with pip and it is not uncommon to have issues when doing this kind of stuff.

## What should be happening ?

Maybe we should install everything from pip to avoid potential python interpreter library mixups.

**Comment by dmsimard** [comment]
Fixed in the pull request.
