### ISSUE TITLE
Docs for ara API client are broken

### ISSUE THREAD

**Issue by erik-overdahl** [ansible-community/ara#454]
Every doc on the `CLI: ara API client` documentation page https://ara.readthedocs.io/en/latest/cli.html shows the following stacktrace instead of the command help output.

```
$ ara --help
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ara/envs/latest/lib/python3.7/site-packages/stevedore/_cache.py", line 159, in _get_data_for_path
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/.cache/python-entrypoints/06820ba4a59b5feb886f151fbe2e7abe6159b41eef950e530220cf4f18e7521d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ara/envs/latest/bin/ara", line 10, in <module>
    sys.exit(main())
  File "/home/docs/checkouts/readthedocs.org/user_builds/ara/envs/latest/lib/python3.7/site-packages/ara/cli/base.py", line 111, in main
    aracli = AraCli()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ara/envs/latest/lib/python3.7/site-packages/ara/cli/base.py", line 90, in __init__
    command_manager=CommandManager("ara.cli"),
  File "/home/docs/checkouts/readthedocs.org/user_builds/ara/envs/latest/lib/python3.7/site-packages/cliff/commandmanager.py", line 63, in __init__
    self._load_commands()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ara/envs/latest/lib/python3.7/site-packages/cliff/commandmanager.py", line 68, in _load_commands
    self.load_commands(self.namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ara/envs/latest/lib/python3.7/site-packages/cliff/commandmanager.py", line 73, in load_commands
    for ep in stevedore.ExtensionManager(namespace):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ara/envs/latest/lib/python3.7/site-packages/stevedore/extension.py", line 136, in __init__
    verify_requirements)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ara/envs/latest/lib/python3.7/site-packages/stevedore/extension.py", line 218, in _load_plugins
    for ep in self.list_entry_points():
  File "/home/docs/checkouts/readthedocs.org/user_builds/ara/envs/latest/lib/python3.7/site-packages/stevedore/extension.py", line 207, in list_entry_points
    eps = list(_cache.get_group_all(self.namespace))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ara/envs/latest/lib/python3.7/site-packages/stevedore/_cache.py", line 179, in get_group_all
    data = self._get_data_for_path(path)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ara/envs/latest/lib/python3.7/site-packages/stevedore/_cache.py", line 162, in _get_data_for_path
    data = _build_cacheable_data(path)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ara/envs/latest/lib/python3.7/site-packages/stevedore/_cache.py", line 110, in _build_cacheable_data
    for name, group_data in real_groups.items():
AttributeError: 'EntryPoints' object has no attribute 'items'
```

**Comment by dmsimard** [comment]
Hi @erik-overdahl and thanks for the issue.

I've also noticed this recently enough: https://github.com/ansible-community/ara/issues/451#issuecomment-1296053818

I haven't got around to troubleshooting it just yet.

**Comment by dmsimard** [comment]
This was fixed at some point but I don't believe we've done anything special about it.

It's possible there was a temporary bug in one of the libraries used or something.
