### ISSUE TITLE
ruamel.yaml 0.18 breaks ara

### ISSUE THREAD

**Issue by noonedeadpunk** [ansible-community/ara#524]
## What is the issue ?

With release of ruamel.yaml 0.18 ara fails the playbook execution with the following error in output:

```
2023-10-24 07:47:54.494053 | ubuntu-jammy | /opt/ansible-runtime/lib/python3.10/site-packages/ara/server/settings.py:306: DeprecationWarning:
2023-10-24 07:47:54.635779 | ubuntu-jammy | dump has been removed, use
2023-10-24 07:47:54.635841 | ubuntu-jammy |
2023-10-24 07:47:54.635849 | ubuntu-jammy |   yaml=YAML(typ='unsafe', pure=True)
2023-10-24 07:47:54.635857 | ubuntu-jammy |   yaml.dump(...)
2023-10-24 07:47:54.635863 | ubuntu-jammy |
2023-10-24 07:47:54.635868 | ubuntu-jammy | instead of
2023-10-24 07:47:54.635874 | ubuntu-jammy |
2023-10-24 07:47:54.635899 | ubuntu-jammy |   yaml.dump({"default": SETTINGS}, settings_file, default_flow_style=False)
2023-10-24 07:47:54.635911 | ubuntu-jammy | [ara] No setting found for SECRET_KEY. Generating a random key...
2023-10-24 07:47:54.635918 | ubuntu-jammy | [ara] Creating data & configuration directory: /root/.ara/server
2023-10-24 07:47:54.635924 | ubuntu-jammy | [ara] Writing default settings to /root/.ara/server/settings.yaml
2023-10-24 07:47:54.635939 | ubuntu-jammy |
```

Bringing version of the package <0.18 solves the issue.

**Comment by dmsimard** [comment]
Hi and thanks for reporting the issue @noonedeadpunk o/

As you pointed out, ruamel.yaml 0.18 was released recently and introduced the change:
![Screenshot from 2023-10-24 16-13-50](https://github.com/ansible-community/ara/assets/1291204/3e709b73-3576-48dc-9225-40974090fa1e)

I checked https://review.opendev.org/c/openstack/openstack-ansible/+/899196 and it's good to know that pinning ruamel.yaml is a valid workaround for now.

We have this note on our usage of ruamel.yaml: https://github.com/ansible-community/ara/blob/dde76744596b031f8a52297a71fee59ba9aeb605/ara/server/settings.py#L12-L17

We'll need to fix this part that writes out the default configuration file:
https://github.com/ansible-community/ara/blob/dde76744596b031f8a52297a71fee59ba9aeb605/ara/server/settings.py#L261-L306

**Comment by noonedeadpunk** [comment]
It looks like, according to the changelog at least, that 0.18.2 should kind of fix the issue:
https://sourceforge.net/p/ruamel-yaml/code/ci/a35908655d678b8463ee6198869a0708b3446e06/

So it should not exit(1) failing the playbook, but just show deprecation message. So might be it's not that bad after all!

**Comment by jonbackhaus-mt** [comment]
This still appears to be a problem as of `0.18.5`, based on my install: 

```
$ ara-manage migrate
[ara] No setting found for SECRET_KEY. Generating a random key...
[ara] Creating data & configuration directory: /home/vscode/.ara/server
[ara] Writing default settings to /home/vscode/.ara/server/settings.yaml
Traceback (most recent call last):
  File "/home/vscode/venv/bin/ara-manage", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/vscode/venv/lib/python3.11/site-packages/ara/server/__main__.py", line 27, in main
    if not os.path.exists(settings.ARA_SETTINGS):
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/home/vscode/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/vscode/venv/lib/python3.11/site-packages/ara/server/settings.py", line 306, in <module>
    yaml.dump({"default": SETTINGS}, settings_file, default_flow_style=False)
  File "/home/vscode/venv/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1251, in dump
    error_deprecation('dump', 'dump', arg="typ='unsafe', pure=True")
  File "/home/vscode/venv/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1039, in error_deprecation
    raise AttributeError(s, name=None)
AttributeError:
"dump()" has been removed, use

  yaml = YAML(typ='unsafe', pure=True)
  yaml.dump(...)

instead of file "/home/vscode/venv/lib/python3.11/site-packages/ara/server/settings.py", line 306

        yaml.dump({"default": SETTINGS}, settings_file, default_flow_style=False)
```

**Comment by dmsimard** [comment]
@jonbackhaus-mt could you please share an output of ``pip freeze`` where ara is intalled ? Thanks.

**Comment by jonbackhaus-mt** [comment]
Sure. We have ara installed in a Python virtual environment as part of our devcontainer, along with a number of other tools (like ansible). Here's the `pip freeze` output: 

```sh
$ pip freeze
aiohttp==3.9.1
aiosignal==1.3.1
ansible==7.6.0
ansible-compat==4.1.10
ansible-core==2.14.13
ansible-lint==6.22.1
ara==1.7.0
asgiref==3.7.2
attrs==23.1.0
autopage==0.5.2
black==23.12.0
boto3==1.33.12
botocore==1.33.12
bracex==2.4
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
cliff==4.4.0
cmd2==2.4.3
cryptography==41.0.7
Django==4.2.8
django-cors-headers==4.3.1
django-filter==23.5
django-health-check==3.17.0
djangorestframework==3.14.0
dynaconf==3.2.4
filelock==3.13.1
frozenlist==1.4.0
idna==3.6
importlib-metadata==7.0.0
Jinja2==3.1.2
jmespath==1.0.1
jsonschema==4.20.0
jsonschema-specifications==2023.11.2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
multidict==6.0.4
mypy-extensions==1.0.0
packaging==23.2
pathspec==0.12.1
pbr==6.0.0
platformdirs==4.1.0
prettytable==3.9.0
pycparser==2.21
Pygments==2.17.2
pyperclip==1.8.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
referencing==0.32.0
requests==2.31.0
resolvelib==0.8.1
rich==13.7.0
rpds-py==0.13.2
ruamel.yaml==0.18.5
ruamel.yaml.clib==0.2.8
s3transfer==0.8.2
six==1.16.0
sqlparse==0.4.4
stevedore==5.1.0
subprocess-tee==0.4.1
tzlocal==5.2
urllib3==2.0.7
wcmatch==8.5
wcwidth==0.2.12
whitenoise==6.6.0
yamllint==1.33.0
yarl==1.9.4
zipp==3.17.0
```

**Comment by dmsimard** [comment]
I didn't realize this was an ongoing issue and wrongly presumed it had been fixed by a later release of ruamel.yaml so I was mistaken, sorry about that.

We will fix this issue in two steps:
1) I will open a pull request to pin the version of ruamel.yaml to <0.18.0 and release a version 1.7.1 of ara such that it can continue to use the same settings code without running into the deprecation.
2) At some point in the not-too-distant future, we can remove the pin and fix the deprecated ``.dump`` usage and eventually release it in 1.7.2 or something along these lines.

**Comment by dmsimard** [comment]
1.7.1rc1 has been released in order to fix this issue: https://fosstodon.org/@ara/111884747920655019

1.7.1 will ship later, most likely tomorrow.

**Comment by dmsimard** [comment]
Closing this since 1.7.1 has been released with the fix.
