### ISSUE TITLE
Cannot get it running on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by dincercelik** [ansible-community/ara#62]
Hi,

Ubuntu 18.04 LTS comes with Python 3 by default but Ara has problems. Please see below.

```
dincer@bozhane:~$ python3 -m ara.setup.action_plugins
/usr/local/lib/python3.6/dist-packages/ara/plugins/action

dincer@bozhane:~$ python3 -m ara.setup.callback_plugins
/usr/local/lib/python3.6/dist-packages/ara/plugins/callback

dincer@bozhane:~$ grep plugins /etc/ansible/ansible.cfg 
## Ansible ships with some plugins that require whitelisting,
## Custom plugins should not need this unless plugin author specifies it.
# enable callback plugins, they can output to stdout but cannot be 'stdout' type.
action_plugins     = /usr/local/lib/python3.6/dist-packages/ara/plugins/action
#become_plugins     = /usr/share/ansible/plugins/become
#cache_plugins      = /usr/share/ansible/plugins/cache
callback_plugins   = /usr/local/lib/python3.6/dist-packages/ara/plugins/callback
#connection_plugins = /usr/share/ansible/plugins/connection
#lookup_plugins     = /usr/share/ansible/plugins/lookup
#inventory_plugins  = /usr/share/ansible/plugins/inventory
#vars_plugins       = /usr/share/ansible/plugins/vars
#filter_plugins     = /usr/share/ansible/plugins/filter
#test_plugins       = /usr/share/ansible/plugins/test
#terminal_plugins   = /usr/share/ansible/plugins/terminal
#strategy_plugins   = /usr/share/ansible/plugins/strategy
# enable inventory plugins, default: 'host_list', 'script', 'auto', 'yaml', 'ini', 'toml'
#enable_plugins = host_list, virtualbox, yaml, constructed

dincer@bozhane:~$ ansible localhost -m ping
 [WARNING]: Skipping plugin (/usr/local/lib/python3.6/dist-packages/ara/plugins/callback/ara_default.py) as it seems to be invalid: No module named ara.clients

localhost | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}

dincer@bozhane:~$ ara-manage runserver
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f8bddbe9598>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib/python3/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/python3/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python3/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/lib/python3/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python3/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/ara/server/urls.py", line 22, in <module>
    from django.urls import include, path
ImportError: cannot import name 'include'
```

**Comment by dmsimard** [comment]
@dincercelik is Django installed ?

When recording data locally, it needs to be installed with the ``[server]`` suffix.

See docs: https://ara.readthedocs.io/en/latest/installation.html

**Comment by dincercelik** [comment]
@dmsimard yes it is. I've installed Ara with pip.

```
dincer@bozhane:~$ python3 -m django --version
1.11.11
```

**Comment by dmsimard** [comment]
That version of Django is insufficient, the requirements that should be installed when picking up the server dependencies are here: https://github.com/ansible-community/ara/blob/92772d0c2e0981d1e977774835161d47812a3320/setup.cfg#L36

**Comment by dincercelik** [comment]
@dmsimard thanks for your help and effort.

That's weird because Django was installed as a dependency for Ara. I think this is not reproducible so closing the issue.

**Comment by spamjq38** [comment]
This installation is a disaster! https://ara.recordsansible.org/
