### ISSUE TITLE
Ara server setup. Manage.py missing

### ISSUE THREAD

**Issue by adahlmanpinterest** [ansible-community/ara#83]
## What component is this about ?
Api server. 

## What is your ARA installation like ?
The install is for an ansible environment that is running masterless. The server running Ara is installed under /opt/ara with the folders belonging to the ara user and group.  
Ubuntu 18.04
apt install python3-venv
/opt/ara/.ara/virtualenv/bin/pip install "ara[server]"
ara@ara:/opt/ara/.ara/virtualenv 
## What is happening ?
Following the documentation on the website I am experiencing a few issues with the setup and install. 
Issue 1)   While running the install fro ara[server] this error appears
                Failed building wheel for PyYAML
                Running setup.py clean for PyYAML
Issue 2) Running from bin` ./ara-manage createsuperuser  --username=admin --email=sre@company.com` results in 
```You have 20 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, api, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.  Traceback (most recent call last):
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auth_user

The above exception was the direct cause of the following exception: Traceback (most recent call last):
  File "./ara-manage", line 11, in <module>
    sys.exit(main())
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/ara/server/__main__.py", line 35, in main
    execute_from_command_line(sys.argv)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 61, in execute
    return super().execute(*args, **options)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 82, in handle
    default_username = get_default_username()
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/contrib/auth/management/__init__.py", line 140, in get_default_username
    auth_app.User._default_manager.get(username=default_username)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/ara/.ara/virtualenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auth_user``` Runing ```'python manage.py migrate``` results in ```python: can't open file 'manage.py': [Errno 2] No such file or directory``` even after using pip to install manage.py. Is there something I'm missing in the documentation?


## What should be happening ?
Users should be created and server started with no python errors.

**Comment by dmsimard** [comment]
@adahlmanpinterest hi and thanks for the issue ! We can do a better job at documenting this.

The error says there are missing database tables because the initial database migrations have not been run. Can you run them with ``python manage.py migrate`` and try again ?

**Comment by adahlmanpinterest** [comment]
Thats what it looked like. I tried running and no luck. ```(virtualenv) ara@ara:/opt/ara/.ara/virtualenv/bin$ python manage.py migrate
python: can't open file 'manage.py': [Errno 2] No such file or directory```

Installing manage.py wasn't working either. Is there a location where it should be living?

**Comment by adahlmanpinterest** [comment]
Looks like manage.py is missing from the pip package. Its in the source.

**Comment by dmsimard** [comment]
> Thats what it looked like. I tried running and no luck. `(virtualenv) ara@ara:/opt/ara/.ara/virtualenv/bin$ python manage.py migrate python: can't open file 'manage.py': [Errno 2] No such file or directory`
> 
> Installing manage.py wasn't working either. Is there a location where it should be living?

OH -- yeah, this is available as ``ara-manage`` when installed so the command would be ``ara-manage migrate``.

**Comment by adahlmanpinterest** [comment]
Looks like that did it! Thanks
